import { PROFILE_LIMITS, QWEN_T2I_DISTILLED_LIMITS } from "./limits";
import type { ComfyImageModelDefinition } from "./types";

export const COMFY_IMAGE_MODELS: ComfyImageModelDefinition[] = [
  // Stable Diffusion 1.x / 2.x
  {
    id: "sd15",
    label: "Stable Diffusion 1.5",
    category: "stable-diffusion",
    comfyNode: "CLIP Text Encode (Prompt)",
    comfyClass: "SD15",
    description:
      "Classic SD1.5. Comma-separated tags with optional weight syntax work well; keep prompts short.",
    profile: "sd15_weighted",
    referenceTokenLimit: 77,
    limitsByDetail: PROFILE_LIMITS.sd15_weighted,
  },
  {
    id: "sd20",
    label: "Stable Diffusion 2.0",
    category: "stable-diffusion",
    comfyNode: "CLIP Text Encode (Prompt)",
    comfyClass: "SD20",
    description:
      "OpenCLIP SD2.0. Natural language or weighted tags; avoid overly long prose.",
    profile: "sd15_weighted",
    referenceTokenLimit: 77,
    limitsByDetail: PROFILE_LIMITS.sd15_weighted,
  },
  {
    id: "sd21",
    label: "Stable Diffusion 2.1",
    category: "stable-diffusion",
    comfyNode: "CLIP Text Encode (Prompt)",
    comfyClass: "SD21",
    description: "SD2.1 base. Similar to SD2.0—concise tags or brief descriptive phrases.",
    profile: "sd15_weighted",
    referenceTokenLimit: 77,
    limitsByDetail: PROFILE_LIMITS.sd15_weighted,
  },

  // SDXL family
  {
    id: "sdxl",
    label: "SDXL Base",
    category: "sdxl",
    comfyNode: "CLIP Text Encode (Prompt)",
    comfyClass: "SDXL",
    description:
      "SDXL dual-encoder. Natural-language scene descriptions outperform bare tag lists.",
    profile: "sdxl_nlp",
    referenceTokenLimit: 77,
    limitsByDetail: PROFILE_LIMITS.sdxl_nlp,
  },
  {
    id: "sdxl-refiner",
    label: "SDXL Refiner",
    category: "sdxl",
    comfyNode: "CLIP Text Encode (Prompt)",
    comfyClass: "SDXLRefiner",
    description:
      "Refiner pass—describe detail and texture refinements, not a wholly new scene.",
    profile: "sdxl_nlp",
    referenceTokenLimit: 77,
    limitsByDetail: PROFILE_LIMITS.sdxl_nlp,
  },
  {
    id: "ssd-1b",
    label: "Segmind SSD-1B",
    category: "sdxl",
    comfyNode: "CLIP Text Encode (Prompt)",
    comfyClass: "SSD1B",
    description: "Compact SDXL-class model. Clear natural-language prompts.",
    profile: "sdxl_nlp",
    referenceTokenLimit: 77,
    limitsByDetail: PROFILE_LIMITS.sdxl_nlp,
  },
  {
    id: "segmind-vega",
    label: "Segmind Vega",
    category: "sdxl",
    comfyNode: "CLIP Text Encode (Prompt)",
    comfyClass: "SegmindVega",
    description: "SDXL-class architecture. Descriptive prose with concrete visual detail.",
    profile: "sdxl_nlp",
    referenceTokenLimit: 77,
    limitsByDetail: PROFILE_LIMITS.sdxl_nlp,
  },

  // SD3 / AuraFlow
  {
    id: "sd3-medium",
    label: "Stable Diffusion 3 Medium",
    category: "sd3",
    comfyNode: "CLIP Text Encode (Prompt)",
    comfyClass: "SD3",
    description:
      "SD3 T5 + CLIP. Longer natural language; quote visible text in double quotes.",
    profile: "sd3_nlp",
    referenceTokenLimit: 512,
    limitsByDetail: PROFILE_LIMITS.sd3_nlp,
  },
  {
    id: "sd3-large",
    label: "Stable Diffusion 3 Large",
    category: "sd3",
    comfyNode: "CLIP Text Encode (Prompt)",
    comfyClass: "SD3",
    description: "Full SD3. Rich descriptive prose with spatial and material detail.",
    profile: "sd3_nlp",
    referenceTokenLimit: 512,
    limitsByDetail: PROFILE_LIMITS.sd3_nlp,
  },
  {
    id: "sd3.5-large",
    label: "Stable Diffusion 3.5 Large",
    category: "sd3",
    comfyNode: "CLIP Text Encode (Prompt)",
    comfyClass: "SD35",
    description: "SD3.5 update. Factual scene prose with strong text rendering support.",
    profile: "sd3_nlp",
    referenceTokenLimit: 512,
    limitsByDetail: PROFILE_LIMITS.sd3_nlp,
  },
  {
    id: "auraflow",
    label: "AuraFlow",
    category: "sd3",
    comfyNode: "CLIP Text Encode (Prompt)",
    comfyClass: "AuraFlow",
    description: "Flow-matching T2I. Clear unified scene descriptions in natural language.",
    profile: "sd3_nlp",
    referenceTokenLimit: 512,
    limitsByDetail: PROFILE_LIMITS.sd3_nlp,
  },

  // Flux family
  {
    id: "flux-dev",
    label: "FLUX.1 Dev",
    category: "flux",
    comfyNode: "CLIP Text Encode (Flux)",
    comfyClass: "Flux",
    description:
      "Full FLUX T2I. Subject-first photographic prose—materials, lighting, camera.",
    profile: "flux_prose",
    referenceTokenLimit: 512,
    limitsByDetail: PROFILE_LIMITS.flux_prose,
    checkpointHint: "flux1-dev.safetensors",
  },
  {
    id: "flux-schnell",
    label: "FLUX.1 Schnell",
    category: "flux",
    comfyNode: "CLIP Text Encode (Flux)",
    comfyClass: "FluxSchnell",
    description: "Fast FLUX variant. Shorter, punchy descriptive prompts.",
    profile: "flux_schnell",
    referenceTokenLimit: 512,
    limitsByDetail: PROFILE_LIMITS.flux_schnell,
  },
  {
    id: "flux2",
    label: "FLUX.2",
    category: "flux",
    comfyNode: "CLIP Text Encode (Flux)",
    comfyClass: "Flux2",
    description: "FLUX.2 foundation. Detailed photographic prose; FLUX ignores negatives.",
    profile: "flux_prose",
    referenceTokenLimit: 512,
    limitsByDetail: PROFILE_LIMITS.flux_prose,
  },
  {
    id: "flux-2-klein",
    label: "FLUX.2 Klein 4B Base",
    category: "flux",
    comfyNode: "CLIP Text Encode (Flux)",
    comfyClass: "Flux2Klein",
    description:
      "Undistilled 4B Klein — 20+ steps, higher CFG. Best for fine-tuning and complex edits.",
    profile: "flux_klein",
    referenceTokenLimit: 512,
    limitsByDetail: PROFILE_LIMITS.flux_klein,
  },
  {
    id: "flux-2-klein-4b-distilled",
    label: "FLUX.2 Klein 4B Distilled",
    category: "flux",
    comfyNode: "CLIP Text Encode (Flux)",
    comfyClass: "Flux2Klein",
    description:
      "4-step distilled 4B Klein. Sub-second previews — euler/simple, cfg 1, exactly 4 steps.",
    profile: "flux_klein",
    referenceTokenLimit: 512,
    limitsByDetail: PROFILE_LIMITS.flux_klein,
  },
  {
    id: "flux-2-klein-9b",
    label: "FLUX.2 Klein 9B Base",
    category: "flux",
    comfyNode: "CLIP Text Encode (Flux)",
    comfyClass: "Flux2Klein9B",
    description:
      "Undistilled 9B Klein — 24 steps, CFG 3.5–4.5, euler/simple. Needs a Base workflow/checkpoint; distilled settings will distort output.",
    profile: "flux_klein",
    referenceTokenLimit: 512,
    limitsByDetail: PROFILE_LIMITS.flux_klein,
    checkpointHint: "flux-2-klein-base-9b.safetensors",
  },
  {
    id: "flux-2-klein-9b-distilled",
    label: "FLUX.2 Klein 9B Distilled",
    category: "flux",
    comfyNode: "CLIP Text Encode (Flux)",
    comfyClass: "Flux2Klein9B",
    description:
      "4-step distilled 9B Klein — fast T2I/edit. Use Optimized KSampler for people; Base is 4-step euler. Complex poses may need Klein 9B Base.",
    profile: "flux_klein",
    referenceTokenLimit: 512,
    limitsByDetail: PROFILE_LIMITS.flux_klein,
  },
  {
    id: "flux-inpaint",
    label: "FLUX Inpaint",
    category: "flux",
    comfyNode: "CLIP Text Encode (Flux)",
    comfyClass: "FluxInpaint",
    description: "FLUX inpainting. Describe what belongs in the masked region only.",
    profile: "flux_prose",
    referenceTokenLimit: 512,
    limitsByDetail: PROFILE_LIMITS.flux_prose,
  },
  {
    id: "chroma",
    label: "Chroma",
    category: "flux",
    comfyNode: "CLIP Text Encode (Flux)",
    comfyClass: "Chroma",
    description: "Chroma flow model. Natural-language scene descriptions.",
    profile: "flux_prose",
    referenceTokenLimit: 512,
    limitsByDetail: PROFILE_LIMITS.flux_prose,
  },
  {
    id: "chroma-radiance",
    label: "Chroma Radiance",
    category: "flux",
    comfyNode: "CLIP Text Encode (Flux)",
    comfyClass: "ChromaRadiance",
    description: "Chroma Radiance variant. Photographic prose with material detail.",
    profile: "flux_prose",
    referenceTokenLimit: 512,
    limitsByDetail: PROFILE_LIMITS.flux_prose,
  },

  // Qwen Image
  {
    id: "qwen-image-edit",
    label: "Qwen-Image-Edit",
    category: "qwen",
    comfyNode: "TextEncodeQwenImageEdit",
    comfyClass: "QwenImage",
    description:
      "Original image-edit encoder. Short, unified scene prose for single-image edits.",
    profile: "qwen_edit",
    referenceTokenLimit: 512,
    limitsByDetail: PROFILE_LIMITS.qwen_edit,
  },
  {
    id: "qwen-image-edit-2511",
    label: "Qwen-Image-Edit-2511",
    category: "qwen",
    comfyNode: "TextEncodeQwenImageEditPlus",
    comfyClass: "QwenImage",
    description:
      "2511 edit model. Explicit keep/change instructions; Figure 1 / Figure 2 for multi-image.",
    profile: "qwen_edit_instruction",
    referenceTokenLimit: 512,
    limitsByDetail: PROFILE_LIMITS.qwen_edit_instruction,
  },
  {
    id: "qwen-image-edit-2511-lightning-4",
    label: "Qwen-Image-Edit-2511 Lightning (4-step)",
    category: "qwen",
    comfyNode: "TextEncodeQwenImageEditPlus",
    comfyClass: "QwenImage",
    description:
      "2511 edit + Lightning 4-step LoRA. Fast edits — use euler/simple, cfg 1, 4 steps in KSampler.",
    profile: "qwen_edit_instruction",
    referenceTokenLimit: 512,
    limitsByDetail: PROFILE_LIMITS.qwen_edit_instruction,
  },
  {
    id: "qwen-image-edit-2511-lightning-8",
    label: "Qwen-Image-Edit-2511 Lightning (8-step)",
    category: "qwen",
    comfyNode: "TextEncodeQwenImageEditPlus",
    comfyClass: "QwenImage",
    description:
      "2511 edit + Lightning 8-step LoRA. Balanced speed/quality — euler/simple, cfg 1, 8 steps.",
    profile: "qwen_edit_instruction",
    referenceTokenLimit: 512,
    limitsByDetail: PROFILE_LIMITS.qwen_edit_instruction,
  },
  {
    id: "qwen-rapid-aio-edit",
    label: "Qwen Rapid AIO (Edit)",
    category: "qwen",
    comfyNode: "Load Checkpoint",
    comfyClass: "QwenImage",
    description:
      "Phr00t Rapid AIO merge (2511 + Lightning baked in). Load Checkpoint + TextEncodeQwenImageEditPlus — 4 steps, cfg 1, optional refs for edit or T2I.",
    profile: "qwen_edit_instruction",
    referenceTokenLimit: 512,
    limitsByDetail: PROFILE_LIMITS.qwen_edit_instruction,
  },
  {
    id: "qwen-rapid-aio-sfw",
    label: "Qwen Rapid AIO SFW",
    category: "qwen",
    comfyNode: "Load Checkpoint",
    comfyClass: "QwenImage",
    description:
      "Phr00t Rapid AIO SFW checkpoint. Dual-purpose T2I/edit merge — euler/beta, 4–8 steps, cfg 1. Generate uses scene prose; Refine can still edit.",
    profile: "qwen_t2i_factual",
    referenceTokenLimit: 512,
    limitsByDetail: QWEN_T2I_DISTILLED_LIMITS,
  },
  {
    id: "qwen-rapid-aio-nsfw",
    label: "Qwen Rapid AIO NSFW",
    category: "qwen",
    comfyNode: "Load Checkpoint",
    comfyClass: "QwenImage",
    description:
      "Phr00t Rapid AIO NSFW checkpoint. Dual-purpose T2I/edit merge — euler_ancestral/sgm_uniform, 4–8 steps, cfg 1. Generate uses scene prose; Refine can still edit.",
    profile: "qwen_t2i_factual",
    referenceTokenLimit: 512,
    limitsByDetail: QWEN_T2I_DISTILLED_LIMITS,
  },
  {
    id: "qwen-image-2512",
    label: "Qwen-Image-2512",
    category: "qwen",
    comfyNode: "CLIPTextEncode",
    comfyClass: "QwenImage",
    description:
      "December T2I update. Factual natural language—color, shape, texture, spatial layout. Use euler/beta; draft CFG ~2.5, Final/Max climb toward 50 steps / CFG ~3.5 (a notch under official CFG 4 to keep chroma natural).",
    profile: "qwen_t2i_factual",
    referenceTokenLimit: 512,
    limitsByDetail: PROFILE_LIMITS.qwen_t2i_factual,
    unetHint: "qwen_image_2512_bf16.safetensors",
    vaeHint: "qwen_image_vae.safetensors",
  },
  {
    id: "qwen-image-2512-lightning-4",
    label: "Qwen-Image-2512 Lightning (4-step)",
    category: "qwen",
    comfyNode: "CLIPTextEncode",
    comfyClass: "QwenImage",
    description:
      "2512 T2I + Lightning 4-step LoRA. ~5× faster — euler/simple, cfg 1, 4 steps in KSampler.",
    profile: "qwen_t2i_factual",
    referenceTokenLimit: 512,
    limitsByDetail: QWEN_T2I_DISTILLED_LIMITS,
    unetHint: "qwen_image_2512_bf16.safetensors",
    vaeHint: "qwen_image_vae.safetensors",
  },
  {
    id: "qwen-image-2512-lightning-8",
    label: "Qwen-Image-2512 Lightning (8-step)",
    category: "qwen",
    comfyNode: "CLIPTextEncode",
    comfyClass: "QwenImage",
    description:
      "2512 T2I + Lightning 8-step LoRA. ~2.5× faster — euler/simple, cfg 1, 8 steps.",
    profile: "qwen_t2i_factual",
    referenceTokenLimit: 512,
    limitsByDetail: QWEN_T2I_DISTILLED_LIMITS,
    unetHint: "qwen_image_2512_bf16.safetensors",
    vaeHint: "qwen_image_vae.safetensors",
  },
  {
    id: "qwen-image-2.0",
    label: "Qwen-Image-2.0",
    category: "qwen",
    comfyNode: "CLIP Text Encode (Qwen)",
    comfyClass: "QwenImage",
    description:
      "Unified T2I + edit foundation. Rich detail targets ~1100–1400 characters.",
    profile: "qwen_t2i_rich",
    referenceTokenLimit: 512,
    limitsByDetail: PROFILE_LIMITS.qwen_t2i_rich,
  },

  // Hunyuan / HiDream
  {
    id: "hunyuan-dit",
    label: "Hunyuan DiT",
    category: "hunyuan",
    comfyNode: "CLIP Text Encode (Prompt)",
    comfyClass: "HunyuanDiT",
    description: "Tencent Hunyuan DiT. Natural-language scene descriptions in Chinese or English.",
    profile: "hunyuan_nlp",
    referenceTokenLimit: 512,
    limitsByDetail: PROFILE_LIMITS.hunyuan_nlp,
  },
  {
    id: "hunyuan-image-2.1",
    label: "Hunyuan Image 2.1",
    category: "hunyuan",
    comfyNode: "CLIP Text Encode (Prompt)",
    comfyClass: "HunyuanImage21",
    description: "Hunyuan Image 2.1. Descriptive prose with spatial and lighting detail.",
    profile: "hunyuan_nlp",
    referenceTokenLimit: 512,
    limitsByDetail: PROFILE_LIMITS.hunyuan_nlp,
  },
  {
    id: "hidream",
    label: "HiDream",
    category: "hunyuan",
    comfyNode: "CLIP Text Encode (Prompt)",
    comfyClass: "HiDream",
    description: "HiDream T2I. Clear unified scene prose with concrete visual attributes.",
    profile: "hunyuan_nlp",
    referenceTokenLimit: 512,
    limitsByDetail: PROFILE_LIMITS.hunyuan_nlp,
  },
  {
    id: "hidream-o1",
    label: "HiDream-O1",
    category: "hunyuan",
    comfyNode: "CLIP Text Encode (Prompt)",
    comfyClass: "HiDreamO1",
    description: "HiDream reasoning T2I. Factual descriptive prompts with spatial clarity.",
    profile: "hunyuan_nlp",
    referenceTokenLimit: 512,
    limitsByDetail: PROFILE_LIMITS.hunyuan_nlp,
  },

  // Other DiT / PixArt / Lumina
  {
    id: "pixart-alpha",
    label: "PixArt-α",
    category: "other-dit",
    comfyNode: "CLIP Text Encode (Prompt)",
    comfyClass: "PixArtAlpha",
    description: "PixArt alpha. Descriptive phrases or short natural-language scenes.",
    profile: "pixart_nlp",
    referenceTokenLimit: 256,
    limitsByDetail: PROFILE_LIMITS.pixart_nlp,
  },
  {
    id: "pixart-sigma",
    label: "PixArt-Σ",
    category: "other-dit",
    comfyNode: "CLIP Text Encode (Prompt)",
    comfyClass: "PixArtSigma",
    description: "PixArt Sigma. Clear scene descriptions with subject and setting.",
    profile: "pixart_nlp",
    referenceTokenLimit: 256,
    limitsByDetail: PROFILE_LIMITS.pixart_nlp,
  },
  {
    id: "lumina2",
    label: "Lumina 2",
    category: "other-dit",
    comfyNode: "CLIP Text Encode (Prompt)",
    comfyClass: "Lumina2",
    description: "Lumina 2 DiT. Natural-language prompts with material and lighting detail.",
    profile: "lumina_nlp",
    referenceTokenLimit: 512,
    limitsByDetail: PROFILE_LIMITS.lumina_nlp,
  },
  {
    id: "z-image",
    label: "Z-Image",
    category: "other-dit",
    comfyNode: "CLIP Text Encode (Prompt)",
    comfyClass: "ZImage",
    description: "Z-Image T2I. Factual scene prose with spatial relationships.",
    profile: "lumina_nlp",
    referenceTokenLimit: 512,
    limitsByDetail: PROFILE_LIMITS.lumina_nlp,
  },
  {
    id: "omnigen2",
    label: "OmniGen2",
    category: "other-dit",
    comfyNode: "CLIP Text Encode (Prompt)",
    comfyClass: "OmniGen2",
    description:
      "OmniGen2 unified model. Instruction-style or scene descriptions; supports references.",
    profile: "omnigen_instruction",
    referenceTokenLimit: 512,
    limitsByDetail: PROFILE_LIMITS.omnigen_instruction,
  },
  {
    id: "anima",
    label: "Anima",
    category: "other-dit",
    comfyNode: "CLIP Text Encode (Prompt)",
    comfyClass: "Anima",
    description: "Anima T2I. Natural-language scene descriptions.",
    profile: "generic_nlp",
    referenceTokenLimit: 512,
    limitsByDetail: PROFILE_LIMITS.generic_nlp,
  },
  {
    id: "kandinsky5",
    label: "Kandinsky 5",
    category: "other-dit",
    comfyNode: "CLIP Text Encode (Prompt)",
    comfyClass: "Kandinsky5",
    description: "Kandinsky 5. Descriptive unified scene prose.",
    profile: "generic_nlp",
    referenceTokenLimit: 512,
    limitsByDetail: PROFILE_LIMITS.generic_nlp,
  },
  {
    id: "kandinsky5-image",
    label: "Kandinsky 5 Image",
    category: "other-dit",
    comfyNode: "CLIP Text Encode (Prompt)",
    comfyClass: "Kandinsky5Image",
    description: "Kandinsky 5 image variant. Clear natural-language prompts.",
    profile: "generic_nlp",
    referenceTokenLimit: 512,
    limitsByDetail: PROFILE_LIMITS.generic_nlp,
  },
  {
    id: "stable-cascade-b",
    label: "Stable Cascade Stage B",
    category: "other-dit",
    comfyNode: "CLIP Text Encode (Prompt)",
    comfyClass: "StableCascadeB",
    description: "Cascade stage B. Brief descriptive prompts—avoid excessive length.",
    profile: "cascade_nlp",
    referenceTokenLimit: 77,
    limitsByDetail: PROFILE_LIMITS.cascade_nlp,
  },
  {
    id: "cosmos-predict2",
    label: "Cosmos Predict2 (Image)",
    category: "other-dit",
    comfyNode: "CLIP Text Encode (Prompt)",
    comfyClass: "CosmosPredict2",
    description: "NVIDIA Cosmos Predict2 image mode. Factual scene descriptions.",
    profile: "generic_nlp",
    referenceTokenLimit: 512,
    limitsByDetail: PROFILE_LIMITS.generic_nlp,
  },

  // Instruct / edit variants
  {
    id: "sd15-instruct-pix2pix",
    label: "SD1.5 InstructPix2Pix",
    category: "instruct-edit",
    comfyNode: "CLIP Text Encode (Prompt)",
    comfyClass: "SD15InstructPix2Pix",
    description:
      "Instruction edit model. Describe the desired change: \"make it sunset\", \"add snow\".",
    profile: "instruct_pix2pix",
    referenceTokenLimit: 77,
    limitsByDetail: PROFILE_LIMITS.instruct_pix2pix,
  },
  {
    id: "sdxl-instruct-pix2pix",
    label: "SDXL InstructPix2Pix",
    category: "instruct-edit",
    comfyNode: "CLIP Text Encode (Prompt)",
    comfyClass: "SDXLInstructPix2Pix",
    description:
      "SDXL instruction editing. Short imperative instructions describing the edit goal.",
    profile: "instruct_pix2pix",
    referenceTokenLimit: 77,
    limitsByDetail: PROFILE_LIMITS.instruct_pix2pix,
  },
  {
    id: "lotus-d",
    label: "Lotus-D",
    category: "instruct-edit",
    comfyNode: "CLIP Text Encode (Prompt)",
    comfyClass: "LotusD",
    description: "Lotus depth/normal auxiliary—describe the scene for conditioning.",
    profile: "generic_nlp",
    referenceTokenLimit: 512,
    limitsByDetail: PROFILE_LIMITS.generic_nlp,
  },
  {
    id: "wan-video",
    label: "WAN Video",
    category: "video",
    comfyNode: "WanVideoTextEncode",
    comfyClass: "WanVideo",
    description:
      "WAN video generation — describe subject motion, camera movement, and temporal continuity.",
    profile: "video_motion",
    referenceTokenLimit: 512,
    limitsByDetail: PROFILE_LIMITS.video_motion,
    checkpointHint: "wan2.2_t2v_high_noise_14B_fp16.safetensors",
  },
  {
    id: "hunyuan-video",
    label: "Hunyuan Video",
    category: "video",
    comfyNode: "HunyuanVideoTextEncode",
    comfyClass: "HunyuanVideo",
    description:
      "Hunyuan video — motion-focused prompts with stable framing and scene continuity.",
    profile: "video_motion",
    referenceTokenLimit: 512,
    limitsByDetail: PROFILE_LIMITS.video_motion,
    checkpointHint: "hunyuan_video_t2v_720p_bf16.safetensors",
  },
  {
    id: "ltx-video",
    label: "LTX Video",
    category: "video",
    comfyNode: "LTXVImgToVideo",
    comfyClass: "LTXV",
    description:
      "LTX Video — concise motion prompts with stable subject identity across frames.",
    profile: "video_motion",
    referenceTokenLimit: 512,
    limitsByDetail: PROFILE_LIMITS.video_motion,
    checkpointHint: "ltx-video-2b-v0.9.safetensors",
  },
  {
    id: "stable-audio",
    label: "Stable Audio",
    category: "audio",
    comfyNode: "CLIPTextEncode",
    comfyClass: "StableAudio",
    description:
      "Stable Audio — describe instruments, texture, tempo, and space for sound generation packs.",
    profile: "audio_sound",
    referenceTokenLimit: 256,
    limitsByDetail: PROFILE_LIMITS.audio_sound,
    checkpointHint: "stable-audio-open.safetensors",
  },
  {
    id: "hunyuan-3d",
    label: "Hunyuan 3D",
    category: "mesh",
    comfyNode: "CLIPTextEncode",
    comfyClass: "Hunyuan3D",
    description:
      "Hunyuan 3D / mesh — describe shape, materials, and silhouette for image-to-mesh scaffolds.",
    profile: "mesh_3d",
    referenceTokenLimit: 256,
    limitsByDetail: PROFILE_LIMITS.mesh_3d,
    checkpointHint: "hunyuan3d.safetensors",
  },
];

export const COMFY_MODEL_IDS = new Set(
  COMFY_IMAGE_MODELS.map((entry) => entry.id),
);

export const DEFAULT_COMFY_MODEL = "qwen-image-2512";

/** Default model for the Video tool (`category: "video"`). */
export const DEFAULT_VIDEO_MODEL = "wan-video";

export const DEFAULT_AUDIO_MODEL = "stable-audio";
export const DEFAULT_MESH_MODEL = "hunyuan-3d";

export const COMFY_MODEL_CATEGORIES: {
  id: ComfyImageModelDefinition["category"];
  label: string;
}[] = [
  { id: "stable-diffusion", label: "Stable Diffusion" },
  { id: "sdxl", label: "SDXL" },
  { id: "sd3", label: "SD3 / AuraFlow" },
  { id: "flux", label: "Flux / Chroma" },
  { id: "qwen", label: "Qwen Image" },
  { id: "hunyuan", label: "Hunyuan / HiDream" },
  { id: "other-dit", label: "PixArt / Lumina / Other" },
  { id: "instruct-edit", label: "Instruct / Edit" },
  { id: "video", label: "Video" },
  { id: "audio", label: "Audio" },
  { id: "mesh", label: "3D Mesh" },
];
