/** Auto-generated by scripts/generate-clothing.mjs — do not edit manually. */
import { CLOTHING_CATALOG_1 } from "./clothing-catalog-1";
import { CLOTHING_CATALOG_2 } from "./clothing-catalog-2";
import { CLOTHING_CATALOG_3 } from "./clothing-catalog-3";

export const ALL_CLOTHING_CATALOG_ENTRIES = [
  ...CLOTHING_CATALOG_1,
  ...CLOTHING_CATALOG_2,
  ...CLOTHING_CATALOG_3,
] as const;
