/** Additional handcrafted scene locations merged into the random pool. */
export const EXTRA_SCENE_LOCATIONS = [
  "Portland Japanese garden maple bridge after rain",
  "Savannah moss-draped square with gas lamp glow",
  "Charleston pastel row house piazza at dusk",
  "Asheville art-deco S&W building corner",
  "Santa Fe adobe compound courtyard gate",
  "Taos Pueblo multi-story ladder access",
  "Marfa minimalist art installation yard",
  "Big Sur Bixby Creek bridge fog line",
  "Joshua Tree boulder camp at star rise",
  "Sedona red rock vortex overlook",
  "White Sands gypsum dune ridge trail",
  "Antelope Canyon light beam floor",
  "Monument Valley butte shadow line",
  "Badlands striped ridge overlook",
  "Crater Lake caldera rim snow edge",
  "Olympic rainforest hall of moss maples",
  "Hoh River drift log jam",
  "Columbia River gorge waterfall mist deck",
  "Multnomah Falls bridge spray zone",
  "Lake Louise turquoise moraine shore",
  "Moraine Lake ten peaks reflection",
  "Jasper Athabasca falls mist rail",
  "Whistler peak alpine meadow hut",
  "Tofino storm beach log tangle",
  "Peggy's Cove granite lighthouse wave cut",
  "Fundy tidal bore mud flat edge",
  "Gaspé Percé rock sea stack base",
  "Churchill polar bear fence observation lane",
  "Churchill aurora borealis tundra boardwalk",
  "Whitehorse Yukon river ice breakup shore",
  "Inuvik pingos frozen tundra field",
  "Iqaluit frozen fjord hamlet lane",
  "Nuuk colorful hillside stair street",
  "Reykjanes lava field steam vent",
  "Snæfellsnes black church lava field",
  "Westfjords cliff fishing hut cove",
  "Myvatn pseudocraters rim walk",
  "Jokulsarlon iceberg lagoon black sand",
  "Skaftafell glacier tongue moraine",
  "Trolltunga cliff shelf above lake",
  "Preikestolen pulpit rock ledge",
  "Geiranger fjord waterfall mist deck",
  "Bergen Bryggen wharf timber row",
  "Tromsø arctic cathedral glass wall",
  "Lofoten red rorbu pier at midnight sun",
  "Svalbard coal town polar bear warning sign lane",
  "Kiruna iron ore mine pit rim",
  "Abisko aurora observation lake shore",
  "Rovaniemi Santa village reindeer fence",
  "Helsinki design district cobble lane",
  "Tallinn old town wall bastion stair",
  "Riga art nouveau facade entry",
  "Vilnius Uzupis bridge declaration wall",
  "Gdansk crane gate waterfront",
  "Wroclaw dwarf statue alley",
  "Brno underground ossuary candle niche",
  "Olomouc astronomical clock plinth",
  "Bled island church bell tower shore",
  "Postojna cave train platform glow",
  "Piran Venetian harbor narrow lane",
  "Kotor fortress switchback stone stair",
  "Mostar Neretva river bank mist",
  "Sarajevo Latin bridge cobble bend",
  "Belgrade Kalemegdan fortress river wall",
  "Skopje stone bridge night market glow",
  "Ohrid lake monastery cliff path",
  "Meteora monastery rock stair landing",
  "Delphi oracle terrace olive grove view",
  "Nafplio harbor fortress stair at dusk",
  "Hydra car-free harbor stone ramp",
  "Symi neoclassical harbor pastel row",
  "Chania Venetian harbor lighthouse base",
  "Santorini Imerovigli caldera stair",
  "Milos white rock lunar beach cove",
  "Naxos Portara temple gate sea frame",
  "Paros marble quarry amphitheater pit",
  "Folegandros cliff village church square",
  "Amalfi lemon terrace coastal stair",
  "Positano vertical village stair cascade",
  "Ravello villa rufolo garden cliff edge",
  "Cinque Terre Manarola harbor rock",
  "Portofino pastel harbor quay",
  "Cinque Terre Vernazza storm harbor",
  "Lake Como bellagio promenade steps",
  "Lake Garda Sirmione castle moat walk",
  "Dolomites Seceda ridge grass slope",
  "Cortina alpine meadow hut porch",
  "Val Gardena larch forest autumn lane",
  "Matera sassi cave dwelling stair",
  "Alberobello trullo stone roof lane",
  "Procida colorful marina ramp",
  "Capri Faraglioni rock boat cove",
  "Elba Napoleonic exile villa terrace",
  "Sicily Taormina Greek theater sea view",
  "Aeolian Stromboli lava flow night glow",
  "Pantelleria dammusi lava stone courtyard",
  "Sardinia Costa Smeralda granite cove",
  "Corsica Bonifacio white cliff harbor",
  "Monaco yacht harbor tunnel exit",
  "Nice Promenade des Anglais pebble shore",
  "Cannes Palais steps red carpet echo",
  "Saint-Tropez harbor pastel fishing boats",
  "Marseille calanque limestone inlet",
  "Avignon broken bridge Rhone mist",
  "Arles Roman arena interior sand",
  "Carcassonne double wall rampart walk",
  "Colmar half-timber canal reflection",
  "Strasbourg Petite France timber bridge",
  "Heidelberg castle ruin terrace view",
  "Rothenburg ob der Tauber wall gate",
  "Neuschwanstein bridge gorge view",
  "Berchtesgaden Eagle's Nest cloud deck",
  "Hallstatt lakeside salt mine stair",
  "Salzburg fortress cliff stair overlook",
  "Innsbruck golden roof lane",
  "Zermatt Matterhorn reflection lake",
  "Jungfraujoch ice palace tunnel",
  "Grindelwald Eiger north face meadow",
  "Lauterbrunnen waterfall valley meadow",
  "Interlaken lake ferry pier mist",
  "Lucerne chapel bridge dawn stillness",
  "Bern arcaded old town bear pit edge",
  "Geneva jet d'eau spray rainbow",
  "Montreux lakeside Freddie Mercury statue quay",
  "Chamonix Mer de Glace ice cave mouth",
  "Annecy canal old town bridge",
  "Gordes lavender hill village overlook",
  "Roussillon ochre cliff path",
  "Aix-en-Provence fountain moss square",
  "Avignon papal palace courtyard shade",
  "Biarritz rock of the virgin wave spray",
  "San Sebastian La Concha bay promenade",
  "Bilbao Guggenheim titanium curve plaza",
  "Santiago cathedral incense haze nave",
  "Porto Ribeira tile facade stair",
  "Sintra Pena palace colorful rampart",
  "Evora Roman temple column row",
  "Obidos walled village gate flower pots",
  "Algarve Benagil sea cave sun shaft",
  "Madeira levada cliff irrigation path",
  "Azores Sete Cidades twin lake rim",
  "Canary Teide lava field observatory pad",
  "Marrakech Jemaa el-Fna spice smoke dusk",
  "Chefchaouen blue alley stair wash",
  "Fes tannery vats terrace overlook",
  "Essaouira Atlantic rampart wave spray",
  "Sahara erg Chebbi dune camp fire circle",
  "Atlas Todra gorge narrow slot wall",
  "Luxor Karnak hypostyle hall shadow",
  "Abu Simbel colossi dawn alignment",
  "Siwa oasis salt lake mirage edge",
  "Cairo citadel mosque courtyard haze",
  "Alexandria bibliotheca seafront promenade",
  "Petra treasury narrow siq exit",
  "Wadi Rum red sand arch camp",
  "Dead Sea salt crust shelf float edge",
  "Jerusalem old city stone ramp stair",
  "Tel Aviv Bauhaus white city balcony row",
  "Haifa Bahai garden terrace cascade",
  "Amman Roman theater upper tier",
  "Wadi Mujib canyon river slot entrance",
  "Dubai frame glass bridge skyline view",
  "Abu Dhabi Sheikh Zayed mosque courtyard",
  "Muscat Mutrah souq harbor corniche",
  "Salalah monsoon khareef mist frankincense grove",
  "Socotra dragon tree plateau mist",
  "Samarkand Registan tile facade noon",
  "Bukhara Kalyan minaret shadow square",
  "Khiva Itchan Kala mud wall gate",
  "Almaty Big Almaty lake glacial shore",
  "Issyk-Kul lakeside yurt camp shore",
  "Tashkent metro station marble hall",
  "Ashgabat white marble monument axis",
  "Tehran Golestan palace mirror hall",
  "Isfahan Imam square fountain mist",
  "Shiraz Eram garden cypress alley",
  "Yazd wind tower alley upward draft",
  "Persepolis stone bull capital platform",
  "Kashan Fin garden pavilion pool",
  "Cappadocia underground city vent shaft",
  "Goreme fairy chimney cave hotel terrace",
  "Pamukkale travertine terrace pool lip",
  "Ephesus library facade marble steps",
  "Sumela monastery cliff face terrace",
  "Gallipoli ANZAC cove cliff path",
  "Istanbul Galata tower rooftop lane",
  "Cappadocia hot air balloon launch field",
  "Bodrum castle harbor rampart walk",
  "Mykonos windmill hill sunset lane",
  "Rhodes medieval moat walk shadow",
  "Corfu olive press stone floor",
  "Kotor bay mirror still morning",
  "Dubrovnik city wall sea bastion",
  "Plitvice wooden footbridge waterfall mist",
  "Zagreb upper town cannon lane",
  "Helsinki Suomenlinna sea fortress rampart",
  "Stockholm metro art cave station platform",
  "Copenhagen Nyhavn canal color row",
  "Oslo opera house marble roof walk",
  "Edinburgh Royal Mile close stair shadow",
  "Glasgow necropolis hill monument view",
  "Isle of Skye Old Man of Storr base",
  "Giant's Causeway hex column shore",
  "Cliffs of Moher Atlantic spray rail",
  "Ring of Kerry coastal ruin headland",
  "Connemara bog boardwalk mist",
  "Dingle peninsula storm beach lane",
  "Kilkenny castle rose garden wall",
  "Bruges canal swan bridge reflection",
  "Ghent Graslei guild house row",
  "Antwerp diamond district art nouveau entry",
  "Luxembourg casemates tunnel candle niche",
  "Liechtenstein Vaduz castle cliff path",
  "Andorra Pyrenees stone village stair",
  "Monaco grand prix tunnel exit curve",
  "Valletta bastion harbor gun port",
  "Mdina silent city limestone gate",
  "Gozo Azure Window collapse rubble cove",
  "Cyprus Troodos pine chapel yard",
  "Rhodes Lindos acropolis sea overlook",
  "Crete Samaria gorge stream crossing",
  "Santorini Akrotiri excavation wall",
  "Meteora monolith summit cable landing",
  "Delos marble lion terrace ruin",
  "Hydra harbor donkey path stone ramp",
  "Tokyo Shimokitazawa vintage shop alley",
  "Kyoto Fushimi Inari torii tunnel mist",
  "Osaka Dotonbori canal neon reflection",
  "Nara deer park temple lantern path",
  "Kanazawa Kenrokuen pond bridge",
  "Shirakawa-go gassho farmhouse snow roof",
  "Hakone onsen outdoor bath steam",
  "Nikko cedar avenue shrine approach",
  "Kamakura Great Buddha moss courtyard",
  "Naoshima art house project courtyard",
  "Teshima art museum concrete oval deck",
  "Seoul Bukchon hanok roofline lane",
  "Busan Gamcheon culture village stair",
  "Jeju haenyeo diving rock shelf",
  "Gyeongju burial mound park path",
  "Taipei Jiufen lantern alley mist",
  "Taroko gorge marble cliff tunnel mouth",
  "Sun Moon Lake pier morning stillness",
  "Hong Kong monster building courtyard well",
  "Macau Ruins of St Paul stair",
  "Guangzhou shamian colonial colonnade",
  "Guilin karst river bamboo raft dock",
  "Zhangjiajie avatar mountain glass bridge",
  "Huangshan granite peak cloud sea stair",
  "Lijiang old town canal stone bridge",
  "Shangri-La Tibetan prayer wheel court",
  "Lhasa potala palace approach stair",
  "Everest base camp prayer flag line",
  "Bhutan tiger's nest cliff approach bend",
  "Kathmandu durbar square temple plinth",
  "Pokhara lake Phewa boat dock mist",
  "Varanasi ghat stone step river mist",
  "Jaipur amber fort mirror hall",
  "Jodhpur blue city rooftop parapet",
  "Kerala backwater houseboat deck",
  "Hampi boulder ruin river coracle shore",
  "Mumbai gateway arch sea spray",
  "Colombo galle face green promenade",
  "Maldives overwater bungalow plank walk",
  "Boracay white beach palm shadow line",
  "Palawan underground river mouth",
  "Banaue rice terrace mud wall path",
  "Angkor wat outer gallery colonnade",
  "Ta Prohm silk-cotton root temple wall",
  "Luang Prabang alms route morning shade",
  "Bagan temple plain hot air shadow",
  "Inle Lake leg-rower channel garden",
  "Chiang Mai moat corner gate shade",
  "Ayutthaya brick prang field grass",
  "Komodo island dragon trail dust",
  "Raja Ampat reef drop-off pier",
  "Uluru base walk cave overhang",
  "Great Barrier Reef pontoon snorkel deck",
  "Milford Sound waterfall cliff face",
  "Rotorua geothermal mud pool boardwalk",
  "Waitomo glowworm cave boat silence",
  "Abel Tasman golden sand estuary",
  "Easter Island moai quarry slope",
  "Torres del Paine granite horn base",
  "Iguazu falls mist catwalk bend",
  "Machu Picchu terrace wall mist",
  "Amazon canopy walkway rope bridge",
  "Pantanal wetland hyacinth channel",
  "Rio sugarloaf cable car summit deck",
  "Cartagena walled city cannon ramp",
  "Medellín metro cable car station",
  "Galapagos tortoise reserve trail dust",
  "Patagonia Perito Moreno glacier face",
  "Tierra del Fuego end-of-world sign post",
  "Antarctica emperor penguin ice shelf camp",
  "Greenland ice sheet meltwater channel",
  "Iceland plane wreck black sand surround",
  "Chernobyl exclusion zone ferris wheel base",
  "Baikonur launch pad service tower foot",
  "Kamchatka valley of geysers boardwalk",
  "Lake Baikal ice pressure ridge shore",
  "DMZ observation binocular rail",
  "Singapore Gardens by the Bay supertree grove",
  "Marina Bay Sands infinity pool edge",
  "Bangkok Wat Arun riverside mosaic stair",
  "Chiang Rai white temple mirror pond",
  "Penang street art alley five-foot way",
  "Melaka river cruise neon quay",
  "Jakarta old town Dutch square",
  "Bali Tegallalang rice terrace overlook",
  "Lombok volcano crater rim mist",
  "Flores Kelimutu tri-color crater lakes",
  "Timor coral reef shallows pier",
  "Papua highland sing-sing ground clearing",
  "Solomon Islands war wreck shallow cove",
  "Fiji coral garden sand channel",
  "Tahiti black sand lagoon fringe",
  "Bora Bora overwater bungalow sunset deck",
  "Samoa lava tube coastal blowhole",
  "Tonga royal tomb stone platform",
  "Vanuatu active volcano ash slope",
  "New Caledonia lagoon nickel-red soil cliff",
  "Norfolk Island pine-lined cliff walk",
  "Lord Howe Island lagoon coral shelf",
  "Kangaroo Island Remarkable Rocks granite",
  "Freycinet Wineglass Bay lookout",
  "Cradle Mountain dove lake boardwalk",
  "Uluru-Kata Tjuta domed rock valley",
  "Kakadu Nourlangie rock art shelter",
  "Broome Cable Beach camel line dusk",
  "Ningaloo reef whale shark snorkel zone",
  "Nullarbor plain roadhouse mirage horizon",
  "Flinders Ranges Wilpena Pound rim",
  "Great Ocean Road Twelve Apostles lookout",
  "Blue Mountains three sisters fog rail",
  "Daintree rainforest river ferry crossing",
  "Fraser Island lake McKenzie dune edge",
  "Aoraki mount cook hooker valley bridge",
  "Fiordland kepler track moss bridge",
  "Wellington cable car hilltop wind",
  "Auckland sky tower shadow harbor",
  "Chatham Islands basalt coast stack",
  "Atacama ALMA antenna array pad",
  "Salar de Uyuni train cemetery rust",
  "Colca canyon condor cross overlook",
  "Lençóis Maranhenses dune lagoon mirror",
  "Fernando de Noronha cliff dive rock",
  "Salvador pelourinho cobble incline",
  "Quito equator monument plaza",
  "Cusco inca stone wall alley",
  "Lake Titicaca reed island edge",
  "South Georgia whaling station rust bay",
  "Falkland islands peat stream crossing",
  "Lapland aurora teepee fire circle edge",
  "North Cape globe monument wind",
  "Aral Sea ship graveyard rust hull",
  "Gobustan mud volcano bubble field",
  "Yerevan cascade complex stone steps",
  "Baku flame towers plaza night",
  "Iranian qanat underground access stair",
  "Mount Ararat foothill monastery view",
  "Van lake akdamar church island pier",
  "Troy archaeological trench wall",
  "Cappadocia hot air balloon launch field at dawn",
  "underground fungal bioluminescent cavern with stone pools",
  "orbital ring habitat observation window above Earth",
  "Martian regolith research dome airlock porch",
  "lunar lava tube habitat entrance with solar arrays",
  "steampunk clockwork city plaza with brass gears",
  "solarpunk vertical farm greenhouse tower atrium",
  "dieselpunk refinery skyline with smoke stacks",
  "retro-futurist monorail station with chrome curves",
  "post-apocalyptic overgrown subway mezzanine",
  "cyberpunk megastructure maintenance catwalk",
  "biopunk algae reactor greenhouse aisle",
  "fantasy elven tree-city rope bridge canopy",
  "dwarven forge hall with magma channels",
  "floating sky island waterfall edge",
  "crystal desert ruin with prismatic light",
  "enchanted library infinite shelf aisle",
  "haunted Victorian nursery with lace curtains",
  "abandoned mall food court with skylight weeds",
  "empty big-box store with fluorescent hum",
  "closed cinema lobby with torn velvet seats",
  "derelict bowling alley with lane reflections",
  "shuttered roller rink with disco ball dust",
  "vacant office cubicle farm after hours",
  "late-night laundromat with spinning drums",
  "24-hour diner with vinyl booths and neon",
  "roadside motel ice machine alcove",
  "truck stop shower corridor at 3am",
  "train yard switching tower overlook",
  "grain elevator dust cloud loading bay",
  "abandoned water park slide dry pool",
  "closed zoo aviary with broken mesh",
  "empty stadium field after final whistle",
  "school gymnasium with folded bleachers",
  "community pool drained for winter",
  "church basement bingo hall storage",
  "fire station bay with polished floor",
  "police evidence locker fluorescent aisle",
  "morgue drawer corridor clinical light",
  "hospital waiting room vending glow",
  "dentist office aquarium tank corner",
  "veterinary surgery prep room tiles",
  "florist walk-in cooler condensation",
  "butcher shop cold room hook row",
  "fish market ice bed stall at dawn",
  "spice merchant sack aisle dust motes",
  "tea house tatami room with scroll alcove",
  "ramen shop counter steam and lantern",
  "sushi bar cedar counter with knife magnet",
  "dim sum cart aisle between round tables",
  "night noodle stall under plastic awning",
  "street taco cart corner with grill smoke",
  "open-air barbecue pit with ember bed",
  "winery barrel cave with chalk marks",
  "brewery taproom with copper lines",
  "distillery rickhouse barrel stacks",
  "cheese cave aging shelf mold bloom",
  "chocolate factory tempering room warmth",
  "bakery proofing room steam haze",
  "patisserie display case morning light",
  "ice cream parlor checker floor booth",
  "candy shop jar wall color grid",
  "toy store aisle with boxed shelves",
  "comic shop longbox row fluorescent",
  "record store listening booth vinyl wall",
  "bookstore rolling ladder fiction aisle",
  "newsstand magazine rack corner glow",
  "pawn shop glass case clutter wall",
  "antique mall booth maze under skylight",
  "flea market tarp stall early setup",
  "farmers market crate row morning shade",
  "Christmas tree lot string light fog",
  "pumpkin patch mud lane wagon rut",
  "county fair midway empty morning",
  "carnival ticket booth closed dawn",
  "boardwalk arcade closed season shutters",
  "beach lifeguard tower off-season sand drift",
  "pier bait shop tackle wall smell",
  "marina dry stack rack winter shrink-wrap",
  "boatyard cradle hull scaffolding",
  "ship chandler rope coil wall",
  "lighthouse fog signal horn shed",
  "coast guard station rescue boat bay",
  "harbor master office chart table",
  "customs house inspection lane",
  "border crossing booth empty lane",
  "toll plaza empty booth night rain",
  "rest area picnic shelter highway hum",
  "gas station canopy puddle reflection",
  "car wash tunnel neon soap foam",
  "auto repair pit with fluorescent glare",
  "junkyard crushed car stack rust",
  "scrap metal yard magnet crane shadow",
  "salvage yard ship container maze",
  "construction site rebar cage floor",
  "crane operator cab height city view",
  "scaffolding alley between brick facades",
  "demolition site exposed floor joists",
  "renovation room with stripped lath walls",
  "attic insulation crawl with rafter light",
  "crawl space dirt floor beam shadow",
  "utility closet water heater hum",
  "boiler room steam pipe maze",
  "electrical substation transformer hum yard",
  "cell tower equipment shack wind",
  "radio tower guy wire anchor pad",
  "wind farm turbine base service door",
  "solar farm inverter row gravel",
  "hydroelectric dam spillway mist zone",
  "nuclear plant cooling tower base plume",
  "coal plant ash pond gray shore",
  "oil refinery flare stack night glow",
  "pipeline valve station prairie isolation",
  "mine headframe hoist cable shadow",
  "quarry bench cut limestone wall",
  "sand pit conveyor dust plume",
  "gravel pit water-filled excavation",
  "asphalt plant silo steam vent",
  "cement batch plant mixer drum",
  "brick kiln chimney heat shimmer",
  "glass furnace glory hole orange glow",
  "steel mill casting floor spark shower",
  "foundry mold floor sand imprint",
  "welding shop curtain flash shadows",
  "machine shop lathe chip floor",
  "woodshop planer shavings pile",
  "cabinet shop spray booth filter wall",
  "upholstery shop fabric bolt wall",
  "tailor shop mannequin row mirror",
  "shoe repair bench awl and last rack",
  "watch repair loupe bench tiny gears",
  "jeweler's bench peg and bur tray",
  "engraver's vise chip copper floor",
  "print shop letterpress chase wall",
  "screen print shop ink squeegee rack",
  "photo darkroom safelight tray glow",
  "film set green screen stage corner",
  "sound stage cyclorama white curve",
  "prop warehouse labeled shelf maze",
  "costume warehouse rolling rack aisle",
  "makeup trailer mirror bulb row",
  "casting office headshot wall grid",
  "agency lobby marble reception desk",
  "coworking space glass phone booth",
  "startup garage whiteboard wall chaos",
  "server closet blinking rack aisle",
  "data center hot aisle containment",
  "trading floor empty after bell",
  "courtroom witness stand wood grain",
  "jury room deliberation table clutter",
  "law library statute shelf ladder",
  "city hall marble stair rotunda",
  "embassy gate flagpole shadow",
  "consulate visa queue rope lane",
  "passport office numbered ticket wall",
  "DMV waiting plastic chair grid",
  "post office sorting bin conveyor",
  "mail room cart stack fluorescent",
  "warehouse fulfillment pick aisle robots",
  "cold storage freezer fog door",
  "distribution dock roll-up door rain",
  "loading bay pallet jack lane",
  "forklift charging station wall",
  "truck loading dock bumpers scuff",
  "rail yard container stack crane shadow",
  "intermodal yard chassis row",
  "air cargo pallet net wrap bay",
  "baggage claim carousel empty loop",
  "airport jet bridge window plane nose",
  "control tower cab panoramic glass",
  "runway edge marker light dusk",
  "helicopter pad windsock gust",
  "hangar floor oil stain pattern",
  "maintenance hangar engine stand bay",
  "flight simulator cab instrument glow",
  "space museum rocket garden pad",
  "planetarium dome star projection seat",
  "observatory dome slit star field",
  "telescope pier mount vibration pad",
  "meteorite lab cutting saw tray",
  "fossil prep lab air scribe dust",
  "paleontology dig site grid string",
  "archaeology trench profile wall",
  "restoration lab gilt leaf table",
  "conservation lab humidified case",
  "herbarium pressed plant drawer",
  "insect collection pin board case",
  "mineral vault fluorescent drawer glow",
  "gem cutting lapidary wheel spray",
  "taxidermy form workshop glass eyes",
  "anatomical model storage shelf",
  "medical school cadaver lab tile",
  "pharmacy compounding counter mortar",
  "laboratory fume hood chemical shelf",
  "clean room bunny suit airlock",
  "microchip fab yellow light bay",
  "robotics lab motion capture grid",
  "VR lab headset charging wall",
  "AI server farm cable waterfall aisle",
  "quantum computer dilution fridge hum",
  "particle detector cavern rock wall",
  "neutrino tank acrylic sphere hall",
  "fusion reactor torus maintenance port",
  "tokamak control room monitor wall",
  "ISS cupola Earth limb view",
  "lunar rover tire track regolith plain",
  "Mars rover sample cache stone circle",
  "Europa ice crack probe landing site",
  "Titan methane lake shore orange haze",
  "Enceladus geyser plume backlit cliff",
  "asteroid mining rig anchor bolt field",
  "O'Neill cylinder interior curved horizon park",
  "generation ship hydroponics spiral aisle",
  "cryosleep chamber corridor frost vent",
  "terraforming dome air scrubber wall",
  "alien ruin hex tile courtyard moss",
  "ancient stargate ring sand burial",
  "portal nexus stone arch energy ripple",
  "wizard tower spiral stair spell shelf",
  "dragon roost cliff cave gold glint",
  "fairy ring mushroom circle dawn mist",
  "goblin market cave stall lantern row",
  "orc war camp palisade mud gate",
  "knight tournament list field pennant",
  "samurai dojo engawa rain line",
  "viking longhouse hearth smoke hole",
  "Roman bath hypocaust tile floor",
  "Greek agora column stump market",
  "Egyptian tomb antechamber offering niche",
  "Mayan ball court stone hoop wall",
  "Inca terrace wall cloud drift",
  "Aztec chinampa floating garden channel",
  "Persian garden quad rill fountain",
  "Mughal charbagh water channel cross",
  "Chinese scholar garden moon gate",
  "Japanese zen rock garden rake lines",
  "Korean palace gate guardian statue",
  "Thai wat golden spire mirror tile",
  "Balinese temple gate split carving",
  "Polynesian marae stone platform sea view",
  "Maori wharenui carved ridge beam",
  "Aboriginal rock shelter ochre hand stencil",
  "Inuit igloo interior lamp glow",
  "Sami lavvu reindeer hide wall",
  "Bedouin black tent carpet floor",
  "Tuareg salt caravan camp star cloth",
  "Berber ksar granary storage cell",
  "Nubian painted house Nile bank",
  "Swahili coral stone house carved door",
  "Zulu kraal cattle byre ash circle",
  "Xhosa rondavel thatch roof yard",
  "Ethiopian tukul round hut eucalyptus fence",
  "Somali nomad camel corral thorn brush",
  "Tuvalu sea wall king tide spray",
  "Kiribati atoll narrow causeway flood line",
  "Marshall Islands WWII bunker reef edge",
  "Micronesia stone money bank yard",
  "Palau jellyfish lake dock",
  "Yap stone money path village",
  "Guam latte stone pillar clearing",
  "Saipan Banzai cliff war memorial",
  "Pitcairn island landing boat cove",
  "Easter Island Anakena palm beach moai",
  "Robben Island limestone quarry cell",
  "Goree island door of no return stone",
  "Elmina castle dungeon sea slot",
  "Great Zimbabwe dry stone wall enclosure",
  "Timbuktu mud mosque minaret shadow",
  "Djenne mosque annual replaster scaffold",
  "Lalibela rock church trench passage",
  "Axum obelisk field dust haze",
  "Gondar castle compound empty courtyard",
  "Simien escarpment gelada cliff ledge",
  "Danakil sulfur salt formation boardwalk",
  "Victoria Falls spray forest gorge bridge",
  "Okavango delta mokoro poling channel",
  "Etosha pan mirage waterhole edge",
  "Sossusvlei dead camelthorn pan dune foot",
  "Fish River Canyon lookout rail",
  "Table Mountain cloud tablecloth edge",
  "Drakensberg basalt amphitheater stream",
  "Kruger granite kopje shade tree base",
  "Zanzibar Stone Town carved door alcove",
  "Lamu dhow harbor morning tide",
  "Diani beach coral rock pool shelf",
] as const;

