/** Auto-generated by scripts/generate-locations.mjs — do not edit manually. */
import { EXTRA_SCENE_LOCATIONS } from "./location-catalog-extra";
import { EXTRA_SCENE_LOCATIONS_2 } from "./location-catalog-extra-2";
import { EXTRA_SCENE_LOCATIONS_3 } from "./location-catalog-extra-3";
import { EXTRA_SCENE_LOCATIONS_4 } from "./location-catalog-extra-4";
import { EXTRA_SCENE_LOCATIONS_5 } from "./location-catalog-extra-5";
import { EXTRA_SCENE_LOCATIONS_6 } from "./location-catalog-extra-6";

export const ALL_EXTRA_SCENE_LOCATIONS: readonly string[] = [
  ...EXTRA_SCENE_LOCATIONS,
  ...EXTRA_SCENE_LOCATIONS_2,
  ...EXTRA_SCENE_LOCATIONS_3,
  ...EXTRA_SCENE_LOCATIONS_4,
  ...EXTRA_SCENE_LOCATIONS_5,
  ...EXTRA_SCENE_LOCATIONS_6,
];
