/** Additional handcrafted scene locations (batch 2). */
export const EXTRA_SCENE_LOCATIONS_2 = [
  "dune-backed brewery yard in summer haze",
  "dawn-lit hospital courtyard at dawn",
  "jade-green canyon overlook with heat shimmer",
  "yellow-stone terrace vineyard row in polar twilight",
  "quartz-lined ticket hall concourse in winter frost",
  "bleached cheese cave with mirage shimmer",
  "upland tram depot yard in sea spray",
  "copper-roofed pagoda terrace in cherry blossom season",
  "vine-draped summit cairn plateau after rain",
  "storm-lashed mausoleum steps at midnight",
  "ash-covered orchard ladder row with falling ash",
  "sun-baked roadside fruit stand in heavy snow",
  "pale rotunda interior under full moon",
  "sandstone yurt camp circle in morning mist",
  "breezy courtroom gallery in morning mist",
  "canopied sports field bleachers in winter frost",
  "starlit ice rink surface during a downpour",
  "emerald arcade corridor in dense fog",
  "glass-walled track infield rail with mirage shimmer",
  "crumbling tollhouse lane in summer haze",
  "gold-leaf fountain plaza at twilight",
  "wind-swept butte overlook with lightning on the horizon",
  "starlit lido deck under full moon",
  "forest-edge canyon overlook in river fog",
  "bronze-age dome observatory floor in winter frost",
  "ruined monastery refectory during a downpour",
  "deserted rotunda interior with heat shimmer",
  "steam-filled ruin chapel nave with firefly dusk",
  "hillside clock tower interior at twilight",
  "neon-lit reading nook alcove with wildfire smoke",
  "indigo smokehouse shed in monsoon mist",
  "balconied bookshop attic with falling ash",
  "wind-scoured storage loft ladder before a storm",
  "heat-hazed fish ladder pool in polar twilight",
  "sun-baked university quad lawn during a downpour",
  "gilded olive grove terrace in cherry blossom season",
  "hillside apothecary cellar under bruised storm clouds",
  "half-submerged medina covered souk in cherry blossom season",
  "palm-fringed sail loft floor in sea spray",
  "pebbled dhow harbor quay in heavy snow",
  "ice-bound volcano observatory deck in autumn color",
  "underground warehouse mezzanine in summer haze",
  "upland archive vault in cherry blossom season",
  "neon-lit motor pool yard with mirage shimmer",
  "wind-swept sanctuary candle wall with falling ash",
  "frosted park bandstand under clear stars",
  "bamboo-shaded granary loft in morning mist",
  "silver-birch windmill cap platform at dusk",
  "overgrown forge courtyard under bruised storm clouds",
  "reflective mead hall hearth in cherry blossom season",
  "sapphire mountain hut porch at dusk",
  "sun-baked signal fire hilltop with hoarfrost stillness",
  "sea-sprayed orchard ladder row with wildfire smoke",
  "wind-swept prison yard wall with drifting pollen",
  "bamboo-shaded outcrop belay ledge under aurora",
  "driftwood-strewn smokehouse shed at dawn",
  "vine-draped lumber mill deck in heat haze",
  "overgrown patio fire pit at dusk",
  "honey-colored planet walk path at midnight",
  "cedar-scented cable car station in cherry blossom season",
  "eroded paper mill sluice in monsoon mist",
  "wind-scoured restaurant terrace in winter frost",
  "gritty sail loft floor in dense fog",
  "twilight track infield rail in sea spray",
  "red-clay snorkel lagoon shelf in winter frost",
  "enchanted circus ring in autumn color",
  "breezy graveyard wall gate in monsoon mist",
  "smoke-stained rail yard switch point with falling ash",
  "flood-damaged rose garden pergola in monsoon mist",
  "grassy shrine torii path in river fog",
  "shingle-roofed rock arch amphitheater in cherry blossom season",
  "spruce-fringed wave-cut platform shore with drifting pollen",
  "thunderhead-lit coffee roastery in winter frost",
  "moonlit ruin chapel nave at dawn",
  "ivy-covered banquet hall with falling ash",
  "deserted ice cave chamber with wildfire smoke",
  "reflective police station yard at twilight",
  "misty patio fire pit with lightning on the horizon",
  "cedar-scented clock tower interior with falling ash",
  "whitewashed spinning mill floor at twilight",
  "deserted station waiting hall with heat shimmer",
  "terracotta theater fly loft at noon",
  "rock-hewn village well square under aurora",
  "overgrown treehouse platform under rolling thunderheads",
  "silent lookout tower cab with drifting pollen",
  "dimly lit mosque courtyard fountain in winter frost",
  "dimly lit clock tower interior in monsoon mist",
  "carved stockyard pen gate under clear stars",
  "deserted dhow harbor quay at noon",
  "steam-filled woodshop floor in late spring",
  "ivy-covered castle bailey at noon",
  "sun-baked estate orangery in morning mist",
  "palm-fringed heliport pad under full moon",
  "fog-draped dhow harbor quay with mirage shimmer",
  "silver-birch bamboo grove clearing with heat shimmer",
  "coral-fringed fortress rampart in golden hour light",
  "underground storm shelter berm in morning mist",
  "bamboo-shaded stargazing platform in monsoon mist",
  "timber-framed backlot street under clear stars",
  "blue-hour skate park bowl in cherry blossom season",
  "dusty thermal mud pool under full moon",
  "basalt summit cairn plateau before a storm",
  "dimly lit ski lodge deck before a storm",
  "heat-hazed woodshop floor under rolling thunderheads",
  "jade-green narrow gorge bridge under full moon",
  "crystal-clear bazaar lane in river fog",
  "reed-thatched zen garden raked gravel in autumn color",
  "harbor-side town hall steps in winter frost",
  "emerald veranda overlooking bay with mirage shimmer",
  "reed-thatched rainforest stream ford with wildfire smoke",
  "granite crevasse edge camp under rolling thunderheads",
  "obsidian brewery yard at midnight",
  "salt-crusted tollhouse lane under bruised storm clouds",
  "slate-roofed lumber mill deck under rolling thunderheads",
  "canopied chicken coop yard in heavy snow",
  "moonlit fieldstone wall lane during a downpour",
  "azure auction house floor under rolling thunderheads",
  "grassy meadow footbridge in monsoon mist",
  "storm-lashed inn courtyard in sea spray",
  "thunderhead-lit factory floor in winter frost",
  "cliffside observatory dome slit during a downpour",
  "lime-washed fairground carousel platform with wildfire smoke",
  "ice-bound spring house stone floor with wildfire smoke",
  "old-growth sunflower field lane in dense fog",
  "heat-hazed trench museum passage in winter frost",
  "deserted overlook rail in golden hour light",
  "wind-scoured greenhouse aisle at twilight",
  "salt-crusted stone circle clearing with wildfire smoke",
  "ochre reservoir spillway before a storm",
  "starlit jazz club stage in heat haze",
  "tidal temple bell courtyard under clear stars",
  "flood-damaged port crane cab after rain",
  "chalk-white bamboo grove clearing under low cloud",
  "crystal-clear storage loft ladder in polar twilight",
  "rain-darkened sanctuary candle wall at twilight",
  "balconied pantry stone cellar under low cloud",
  "sunken gondola station in heavy snow",
  "yellow-stone fishing hut pier with drifting pollen",
  "cypress-lined veranda overlooking bay in dense fog",
  "gilded fjord village quay with heat shimmer",
  "snow-dusted fog-bound pier under bruised storm clouds",
  "hand-painted bench overlook at dusk",
  "thunderhead-lit ocean cliff path in morning mist",
  "turquoise inn courtyard with firefly dusk",
  "canopied lake house dock in polar twilight",
  "crumbling tropical fish pond deck in dense fog",
  "yellow-stone granary loft in winter frost",
  "breezy bell tower stair with drifting pollen",
  "canopied train carriage depot under low cloud",
  "rain-darkened jungle camp clearing in autumn color",
  "bamboo-shaded glasshouse corridor with drifting pollen",
  "iron-clad community garden plot at midnight",
  "ochre patio fire pit in heat haze",
  "basalt tidal cave shelf at midnight",
  "wind-scoured sculpture garden path with heat shimmer",
  "slate-roofed dune slack hollow in summer haze",
  "canopied pantry stone cellar under aurora",
  "rose-colored market square arcades during a downpour",
  "petroleum-stained pilgrim hostel yard with hoarfrost stillness",
  "underground fountain plaza at noon",
  "marble thermal mud pool with heat shimmer",
  "pine-scented plaza colonnade in heat haze",
  "slate-roofed studio backlot alley with drifting pollen",
  "shingle-roofed graveyard wall gate in morning mist",
  "ruined hot spring pool in heat haze",
  "copper-roofed thermal mud pool in polar twilight",
  "granite jazz club stage in heat haze",
  "obsidian wave-cut platform shore in heavy snow",
  "moonlit florist greenhouse under aurora",
  "hidden mosque courtyard fountain after rain",
  "dawn-lit quarry lake edge with wildfire smoke",
  "cloud-wrapped rope bridge crossing with hoarfrost stillness",
  "petroleum-stained joss house courtyard in winter frost",
  "hillside snowfield camp in sea spray",
  "dimly lit pier end gazebo with hoarfrost stillness",
  "ancient rail yard switch point at twilight",
  "scaffolded catacomb passage under clear stars",
  "underground dried riverbed crossing with firefly dusk",
  "dew-covered turkish bath dome pool in autumn color",
  "canopied seawall promenade in morning mist",
  "knotty-pine circus ring with mirage shimmer",
  "canopied glasshouse corridor under low cloud",
  "twilight zoo habitat moat edge in golden hour light",
  "terracotta pagoda terrace under aurora",
  "timber-framed wharf crane shadow in monsoon mist",
  "neon-lit cable car station in morning mist",
  "dune-backed tannery vat row at midnight",
  "smoke-stained smokehouse shed at noon",
  "quartz-lined tannery vat row in polar twilight",
  "steam-filled marina fuel dock in sea spray",
  "obsidian desert arroyo bend with lightning on the horizon",
  "straw-roofed glacier cave mouth with heat shimmer",
  "shingle-roofed ski lodge deck in river fog",
  "mirror-still hayfield lane with drifting pollen",
  "dusty community garden plot with wildfire smoke",
  "cliffside fairground carousel platform under aurora",
  "mud-brick opera house foyer with firefly dusk",
  "candlelit golf clubhouse terrace after rain",
  "lava-black passage tomb entrance in river fog",
  "sea-sprayed mission courtyard in sea spray",
  "knotty-pine inn courtyard under low cloud",
  "gold-leaf signal fire hilltop in morning mist",
  "granite playground after rain in monsoon mist",
  "timber-framed velodrome track curve under aurora",
  "mud-brick assembly hall before a storm",
  "sea-sprayed dune slack hollow in dense fog",
  "crumbling garden maze center at midnight",
  "honey-colored glasshouse corridor before a storm",
  "tidal mountain hut porch in golden hour light",
  "rust-red veranda overlooking bay in winter frost",
  "starlit lumber mill deck with firefly dusk",
  "rust-red wharf crane shadow under aurora",
  "glass-walled oyster farm rack line in golden hour light",
  "moonlit ice cave chamber in river fog",
  "cloud-wrapped hospital courtyard under low cloud",
  "gilded manor kitchen garden with mirage shimmer",
  "dune-backed pump house intake under aurora",
  "glacial crystal shop basement in summer haze",
  "twilight sea cave mouth with mirage shimmer",
  "rust-red fish ladder pool in summer haze",
  "cloud-wrapped fog-bound pier under rolling thunderheads",
  "verdant refectory hall in river fog",
  "underground coral atoll lagoon with drifting pollen",
  "azure tannery vat row in dense fog",
  "overgrown mine cart tunnel under full moon",
  "heat-hazed bird sanctuary blind before a storm",
  "bioluminescent hospital courtyard with mirage shimmer",
  "narrow workshop annex yard in summer haze",
  "cloud-wrapped steam locomotive shed at dusk",
  "sun-baked ruin chapel nave before a storm",
  "tidal vaulted cellar aisle in winter frost",
  "narrow lookout tower cab in dense fog",
  "gold-leaf water tower base in dense fog",
  "cypress-lined tribunal steps after rain",
  "scaffolded airfield hangar with firefly dusk",
  "eroded pod village boardwalk at dusk",
  "sandstone arcade corridor under low cloud",
  "ochre spinning mill floor in monsoon mist",
  "shingle-roofed cable car station under full moon",
  "dimly lit lookout tower cab after rain",
  "candlelit tunnel portal mouth after rain",
  "dew-covered spinning mill floor with firefly dusk",
  "ruined spinning mill floor under bruised storm clouds",
  "dune-backed station waiting hall during a downpour",
  "wind-scoured jetty end at twilight",
  "dew-covered tollhouse lane with mirage shimmer",
  "gold-leaf jazz club stage at dusk",
  "yellow-stone watchmaker shop window with wildfire smoke",
  "hidden steam locomotive shed in heavy snow",
  "flood-damaged florist greenhouse in heavy snow",
  "bronze-age rec center gym after rain",
  "misty plaza colonnade under clear stars",
  "gilded pier end gazebo after rain",
  "pale terrace vineyard row under clear stars",
  "cedar-scented storage loft ladder at dusk",
  "salt-crusted grotto pool with wildfire smoke",
  "fog-draped campground fire ring with wildfire smoke",
  "dimly lit mosque courtyard fountain at twilight",
  "volcanic botanical conservatory at dawn",
  "dew-covered herb garden terrace under aurora",
  "abandoned zipline launch deck in dense fog",
  "terracotta patio fire pit at twilight",
  "flood-damaged castle bailey at midnight",
  "vine-draped club backstage with hoarfrost stillness",
  "mirror-still radio tower compound at noon",
  "terracotta stockyard pen gate in cherry blossom season",
  "bioluminescent smokehouse shed under aurora",
  "whitewashed brickyard kiln at dusk",
  "shadowed fortress rampart under low cloud",
  "dune-backed chapel ruin in late spring",
  "curved stone circle clearing in summer haze",
  "cypress-lined museum rotunda under low cloud",
  "breezy mosque courtyard fountain with drifting pollen",
  "chalk-white winter garden glass dome with lightning on the horizon",
  "torch-lit theater fly loft in summer haze",
  "obsidian lantern festival street in polar twilight",
  "midnight playground after rain before a storm",
  "honey-colored deck overlooking valley in dense fog",
  "sea-sprayed wave-cut platform shore in sea spray",
  "copper-roofed carriage house with firefly dusk",
  "salt-crusted archive vault in monsoon mist",
  "shingle-roofed graveyard wall gate in polar twilight",
  "obsidian quay stone steps in golden hour light",
  "weathered creamery floor at dusk",
  "bronze-age joss house courtyard in cherry blossom season",
  "misty lido deck with lightning on the horizon",
  "tidal turkish bath dome pool at midnight",
  "pale town hall steps in heat haze",
  "hidden manor kitchen garden in river fog",
  "twilight storm shelter berm in cherry blossom season",
  "polished chicken coop yard at dusk",
  "verdant oyster farm rack line in winter frost",
  "granite peninsula tip trail in morning mist",
  "iron-clad sanctuary candle wall in late spring",
  "breezy statue plaza base under low cloud",
  "autumn wellness retreat deck with heat shimmer",
  "terracotta library reading room in cherry blossom season",
  "petroleum-stained castle bailey in late spring",
  "ochre lagoon mangrove edge in golden hour light",
  "heat-hazed opera house foyer in morning mist",
  "open-air tundra research hut in winter frost",
  "honey-colored taxi rank corner at dawn",
  "canopied rice paddy bund path during a downpour",
  "pebbled pagoda terrace in monsoon mist",
  "pink-salt florist greenhouse under aurora",
  "beached community garden plot in golden hour light",
  "ice-bound vineyard crush pad at dawn",
  "rock-hewn jetty end in cherry blossom season",
  "tapestry-lined playground after rain with lightning on the horizon",
  "terracotta archipelago cove in winter frost",
  "ice-bound tundra research hut at dusk",
  "dune-backed basement boiler room with firefly dusk",
  "curved desert arroyo bend under low cloud",
  "midnight embassy courtyard at dawn",
  "ice-bound gymnasium floor in heat haze",
  "rose-colored heliport pad in cherry blossom season",
  "weathered pavilion on lake with firefly dusk",
  "polished lookout tower cab in polar twilight",
  "bleached sports field bleachers after rain",
  "wrought-iron wharf crane shadow in monsoon mist",
  "mirror-still cottage garden in dense fog",
  "deserted orchard ladder row in golden hour light",
  "torch-lit press room floor under aurora",
  "quartz-lined veranda overlooking bay under rolling thunderheads",
  "harbor-side orchard ladder row with hoarfrost stillness",
  "knotty-pine zipline launch deck in autumn color",
  "monsoon-soaked mill race channel under rolling thunderheads",
  "wind-scoured customs warehouse with firefly dusk",
  "beached pump house intake before a storm",
  "coral-fringed mead hall hearth under rolling thunderheads",
  "torch-lit garden maze center in summer haze",
  "steam-filled swamp cypress knee grove at twilight",
  "narrow treehouse platform under full moon",
  "storm-lashed zoo habitat moat edge in heavy snow",
  "glacial memorial amphitheater after rain",
  "flood-damaged canal lock house in heavy snow",
  "quartz-lined campground fire ring under full moon",
  "moonlit golf clubhouse terrace in polar twilight",
  "eroded jetty end during a downpour",
  "black-stone mountain hut porch with drifting pollen",
  "wind-swept lookout tower cab during a downpour",
  "carved winter garden glass dome under low cloud",
  "crumbling aquarium tunnel under bruised storm clouds",
  "red-clay tower bridge walkway in sea spray",
  "old-growth prison yard wall in sea spray",
  "sapphire submarine pen gate under clear stars",
  "jade-green crystal shop basement during a downpour",
  "canopied canyon overlook with heat shimmer",
  "quartz-lined water tower base in sea spray",
  "broken pioneer cabin clearing with falling ash",
  "weathered butte overlook in morning mist",
  "straw-roofed river bend sandbar with wildfire smoke",
  "grassy stockyard pen gate at midnight",
  "wind-scoured racecourse paddock at midnight",
  "narrow sports field bleachers at dawn",
  "rose-colored community garden plot with firefly dusk",
  "copper-roofed market square arcades in river fog",
  "old-growth mission courtyard under bruised storm clouds",
  "lichen-stained shrine torii path under low cloud",
  "yellow-stone floating dock under full moon",
  "frosted tram depot yard in late spring",
  "snow-dusted foundry floor at twilight",
  "gilded locksmith shop bench during a downpour",
  "half-submerged ranch corral gate with falling ash",
  "harbor-side lime kiln ruin in winter frost",
  "mirror-still hayfield lane with lightning on the horizon",
  "tidal kiosk square under rolling thunderheads",
  "rust-red fairground carousel platform in monsoon mist",
  "deserted prison yard wall with lightning on the horizon",
  "arched ticket hall concourse at midnight",
  "neon-lit track infield rail with heat shimmer",
  "marble stadium tunnel mouth under low cloud",
  "pine-scented spice market aisle in monsoon mist",
  "lava-black watchmaker shop window in morning mist",
  "reflective ballroom balcony with lightning on the horizon",
  "torch-lit sanctuary candle wall under aurora",
  "bleached spinning mill floor in heat haze",
  "cedar-scented rock arch amphitheater with falling ash",
  "sun-bleached fortress rampart at dawn",
  "ochre ferry terminal in heat haze",
  "granite museum rotunda at noon",
  "flood-damaged cottage garden with drifting pollen",
  "weathered bowling alley lane at midnight",
  "pebbled pavilion on lake in river fog",
  "tidal police station yard in heat haze",
  "thunderhead-lit lodge great room in monsoon mist",
  "glass-walled basement boiler room at dawn",
  "sea-sprayed crevasse edge camp with wildfire smoke",
  "sapphire museum rotunda under full moon",
  "broken gymnasium floor in summer haze",
  "ruined airfield hangar under clear stars",
  "honey-colored passage tomb entrance in sea spray",
  "misty community garden plot with hoarfrost stillness",
  "bleached aquarium tunnel under rolling thunderheads",
  "old-growth monastery refectory before a storm",
  "whitewashed lido deck in autumn color",
  "dimly lit stargazing platform under clear stars",
  "petroleum-stained greenhouse aisle in monsoon mist",
  "cobbled catacomb passage in dense fog",
  "tapestry-lined perfume distillery room during a downpour",
  "pine-scented forge courtyard with wildfire smoke",
  "autumn oil pier catwalk under low cloud",
  "driftwood-strewn corn maze path in polar twilight",
  "weathered opera house foyer in cherry blossom season",
  "ivy-covered soap factory courtyard in river fog",
  "silver-birch waiting pier shelter in cherry blossom season",
  "crumbling sail loft floor with drifting pollen",
  "pebbled rope bridge crossing at midnight",
  "sandstone orchid house bench with lightning on the horizon",
  "tidal lime kiln ruin in cherry blossom season",
  "hillside lumber mill deck at midnight",
  "bamboo-shaded ice cave chamber at twilight",
  "rain-darkened factory floor in cherry blossom season",
  "scaffolded crystal shop basement under bruised storm clouds",
  "straw-roofed gondola station with mirage shimmer",
  "granite skate park bowl at twilight",
  "candlelit sports field bleachers in late spring",
  "pink-salt rice paddy bund path in heat haze",
  "candlelit club backstage at twilight",
  "snow-dusted dining hall with falling ash",
  "tapestry-lined lagoon mangrove edge in monsoon mist",
  "bronze-age university quad lawn under bruised storm clouds",
  "rust-red signal fire hilltop with mirage shimmer",
  "pebbled maelstrom viewpoint under aurora",
  "canopied sports field bleachers under rolling thunderheads",
  "crumbling tannery vat row under clear stars",
  "timber-framed tower bridge walkway in winter frost",
  "harbor-side hill fort ditch at dusk",
  "polished embassy courtyard in morning mist",
  "overgrown winter garden glass dome at dawn",
  "sodium-lit sea cave mouth with hoarfrost stillness",
  "hand-painted city gate passage with mirage shimmer",
  "cobbled memorial amphitheater in autumn color",
  "weathered mountain hut porch during a downpour",
  "lime-washed glacier cave mouth at midnight",
  "vine-draped gymnasium floor with mirage shimmer",
  "wrought-iron courtyard fountain with firefly dusk",
  "ruined brewery yard in sea spray",
  "timber-framed pump house intake in sea spray",
  "knotty-pine workshop annex yard with wildfire smoke",
  "balconied city gate passage in heavy snow",
  "mud-brick office atrium in river fog",
  "grassy cheese cave with drifting pollen",
  "ochre stone circle clearing under aurora",
  "monsoon-soaked glacier cave mouth under low cloud",
  "cloud-wrapped fishing hut pier with firefly dusk",
  "overgrown waiting pier shelter with mirage shimmer",
  "ruined spring house stone floor under rolling thunderheads",
  "emerald farm silo base in dense fog",
  "tapestry-lined locksmith shop bench with firefly dusk",
  "sandstone vineyard crush pad in river fog",
  "cliffside sculpture garden path in monsoon mist",
  "grassy mountain hut porch at midnight",
  "glass-walled promenade band shell in monsoon mist",
  "scaffolded fog-bound pier in dense fog",
  "basalt harbor breakwater in polar twilight",
  "hand-painted fortress rampart in polar twilight",
  "reflective village well square in dense fog",
  "beached sanctuary candle wall under bruised storm clouds",
  "crumbling lime kiln ruin with firefly dusk",
  "lichen-stained drawbridge tower in morning mist",
  "ancient warehouse mezzanine at noon",
  "polished soundstage alley set under bruised storm clouds",
  "honey-colored pilgrim hostel yard under aurora",
  "heat-hazed fishing hut pier with heat shimmer",
  "cobbled guard tower base in heat haze",
  "frosted orchard ladder row in heat haze",
  "carved bridge underpass with firefly dusk",
  "scaffolded lime kiln ruin in monsoon mist",
  "patchwork rice paddy bund path in polar twilight",
  "reed-thatched lodge great room with lightning on the horizon",
  "coral-fringed sports field bleachers under full moon",
  "frosted chapel ruin with hoarfrost stillness",
  "candlelit floating dock in summer haze",
  "midnight plantation veranda under full moon",
  "starlit pond lily pad edge during a downpour",
  "flood-damaged trench museum passage in dense fog",
  "open-air rainforest stream ford in dense fog",
  "lichen-stained lime kiln ruin with falling ash",
  "tidal stockyard pen gate with mirage shimmer",
  "quartz-lined turkish bath dome pool with firefly dusk",
  "cobbled dune slack hollow at noon",
  "wind-scoured marsh boardwalk with lightning on the horizon",
  "marble hot spring pool in dense fog",
  "straw-roofed restaurant terrace in winter frost",
  "cypress-lined brewery yard in golden hour light",
  "spruce-fringed assembly hall with heat shimmer",
  "gilded seawall promenade under rolling thunderheads",
  "ash-covered slaughterhouse yard under clear stars",
  "narrow golf clubhouse terrace under low cloud",
  "heat-hazed steam locomotive shed under rolling thunderheads",
  "steam-filled hayfield lane in cherry blossom season",
  "azure dining hall before a storm",
  "rust-red pier end gazebo in monsoon mist",
  "sun-bleached dog park gate in morning mist",
  "sapphire amphitheater tier with mirage shimmer",
  "verdant ruin chapel nave with firefly dusk",
  "wrought-iron amphitheater tier at dawn",
  "terracotta dockside warehouse under clear stars",
  "pine-scented synagogue courtyard in polar twilight",
  "wrought-iron lantern festival street under clear stars",
  "moonlit campground fire ring at twilight",
  "carved ruin chapel nave at dawn",
  "red-clay dining hall with drifting pollen",
  "half-submerged highland bothy before a storm",
  "cliffside wetland bird hide at midnight",
  "blue-hour sea cave mouth in river fog",
  "hillside ridge line cairn at twilight",
  "scaffolded desert arroyo bend under full moon",
  "blue-hour courtyard fountain at midnight",
  "arched street market tarp row before a storm",
  "ruined lime kiln ruin at dawn",
  "rust-red ghost town main street in winter frost",
  "blue-hour abbey crypt in cherry blossom season",
  "silver-birch archipelago cove with falling ash",
  "shadowed crystal shop basement in monsoon mist",
  "straw-roofed houseboat deck in polar twilight",
  "timber-framed ballroom balcony in morning mist",
  "rust-red customs warehouse in autumn color",
  "abandoned zoo habitat moat edge in heavy snow",
  "moss-covered guard tower base in heat haze",
  "dune-backed windmill cap platform under aurora",
  "red-clay ranch corral gate in late spring",
  "monsoon-soaked radio tower compound with falling ash",
  "balconied stadium tunnel mouth after rain",
  "rock-hewn synagogue courtyard at noon",
  "sun-bleached quarry lake edge after rain",
  "red-clay beach cave in cherry blossom season",
  "overgrown narrow gorge bridge with heat shimmer",
  "rock-hewn sunflower field lane in autumn color",
  "dune-backed barn loft at dusk",
  "slate-roofed woodshop floor under rolling thunderheads",
  "yellow-stone redwood boardwalk in winter frost",
  "crystal-clear wellness retreat deck in golden hour light",
  "shingle-roofed turnpike rest stop in cherry blossom season",
  "silver-birch pier end gazebo with wildfire smoke",
  "scaffolded aviary dome with mirage shimmer",
  "overgrown roadside fruit stand during a downpour",
  "yellow-stone chicken coop yard at midnight",
  "sea-sprayed racecourse paddock under clear stars",
  "wind-swept rice paddy bund path with drifting pollen",
  "breezy market square arcades under low cloud",
  "balconied mine cart tunnel in summer haze",
  "misty telegraph hill viewpoint with hoarfrost stillness",
  "beached woodshop floor with hoarfrost stillness",
  "cedar-scented winery tasting room in winter frost",
  "volcanic brickyard kiln during a downpour",
  "dune-backed mine cart tunnel in autumn color",
  "smoke-stained ruin chapel nave under full moon",
  "deserted hotel rooftop pool with hoarfrost stillness",
  "wind-swept bus depot in dense fog",
  "storm-lashed quay stone steps in late spring",
  "waterlogged slaughterhouse yard under full moon",
  "silent rice paddy bund path in autumn color",
  "copper-roofed moorland trail crest in autumn color",
  "glacial orchard ladder row with mirage shimmer",
  "open-air music hall balcony with mirage shimmer",
  "chalk-white garden maze center in river fog",
  "gilded tennis court fence line in polar twilight",
  "broken tundra research hut under clear stars",
  "dune-backed heliport pad in late spring",
  "lime-washed olive grove terrace at noon",
  "pine-scented surf break rock shelf at dusk",
  "glacial colonnade walk at twilight",
  "tapestry-lined dog park gate under clear stars",
  "breezy volleyball court sand under low cloud",
  "rose-colored overlook rail under aurora",
  "moss-covered backlot street in autumn color",
  "ochre reservoir spillway in late spring",
  "snow-dusted lumber mill deck under low cloud",
  "moss-covered coral atoll lagoon in golden hour light",
  "bamboo-shaded train carriage depot at midnight",
  "ochre reading nook alcove in heat haze",
  "cloud-wrapped prison yard wall at twilight",
  "pebbled highland bothy in late spring",
  "dune-backed rope bridge crossing in heat haze",
  "marble concert hall lobby with heat shimmer",
  "shingle-roofed temple bell courtyard in polar twilight",
  "ivy-covered gymnasium floor with drifting pollen",
  "polished sculpture garden path under bruised storm clouds",
  "wind-swept drawbridge tower with drifting pollen",
  "silver-birch cable car station in morning mist",
  "whitewashed tool shed yard in late spring",
  "old-growth castle bailey before a storm",
  "autumn tennis court fence line in autumn color",
  "indigo cheese cave in golden hour light",
  "starlit estate orangery at noon",
  "coral-fringed bowling alley lane after rain",
  "bleached circus ring at twilight",
  "mud-brick fairground carousel platform in monsoon mist",
  "curved farm silo base at dusk",
  "overgrown covered bridge interior with wildfire smoke",
  "autumn salt pan crystalline flat under clear stars",
  "neon-lit drawbridge tower under clear stars",
  "broken pioneer cabin clearing with mirage shimmer",
  "forest-edge florist greenhouse in monsoon mist",
  "petroleum-stained synagogue courtyard with hoarfrost stillness",
  "harbor-side tollhouse lane with hoarfrost stillness",
  "torch-lit art gallery annex in golden hour light",
  "wind-swept tea plantation terrace under clear stars",
  "polished cabin porch with heat shimmer",
  "quartz-lined copper mine shaft at dusk",
  "misty tennis court fence line in late spring",
  "ice-bound pier end gazebo in morning mist",
  "harbor-side reservoir spillway before a storm",
  "balconied mission courtyard in heat haze",
  "ash-covered street market tarp row with mirage shimmer",
  "midnight cheese cave under clear stars",
  "straw-roofed apothecary cellar in heavy snow",
  "gold-leaf rope bridge crossing in heavy snow",
  "candlelit ruin chapel nave with lightning on the horizon",
  "sun-bleached rotunda interior with wildfire smoke",
  "rain-darkened desert arroyo bend under full moon",
  "smoke-stained island lighthouse base with firefly dusk",
  "sea-sprayed rock arch amphitheater in cherry blossom season",
  "bioluminescent waterfall base pool before a storm",
  "bronze-age waiting pier shelter under clear stars",
  "beached workshop annex yard in golden hour light",
  "timber-framed palace garden gate with heat shimmer",
  "starlit bench overlook under rolling thunderheads",
  "knotty-pine mead hall hearth in autumn color",
  "ivy-covered pavilion on lake with heat shimmer",
  "sandstone salt pan crystalline flat in golden hour light",
  "candlelit chapel ruin under clear stars",
  "candlelit subway mezzanine under low cloud",
  "arched mill race channel in autumn color",
  "tidal patio fire pit under full moon",
  "breezy outcrop belay ledge at dawn",
  "candlelit rock arch amphitheater with falling ash",
  "torch-lit smokehouse shed after rain",
  "blue-hour sea cave mouth at dawn",
  "forest-edge dome observatory floor under clear stars",
  "heat-hazed opera house foyer with mirage shimmer",
  "ivy-covered refectory hall with wildfire smoke",
  "forest-edge train carriage depot in sea spray",
  "sandstone reading nook alcove with lightning on the horizon",
  "silver-birch fog-bound pier at twilight",
  "sapphire ocean cliff path with lightning on the horizon",
  "torch-lit pioneer cabin clearing in morning mist",
  "flood-damaged tropical fish pond deck at dawn",
  "cliffside maelstrom viewpoint at dusk",
  "dune-backed watchmaker shop window under full moon",
  "vine-draped crystal shop basement in winter frost",
  "coral-fringed metro platform at dawn",
  "tapestry-lined lighthouse fog signal shed at dusk",
  "dawn-lit oyster farm rack line in sea spray",
  "carved pub beer garden with wildfire smoke",
  "flood-damaged ranch corral gate at twilight",
  "dawn-lit prairie windmill base at midnight",
  "wrought-iron rope bridge crossing after rain",
  "flood-damaged sea arch tide pool under bruised storm clouds",
  "shingle-roofed barn loft before a storm",
  "upland grotto pool with lightning on the horizon",
  "rust-red spa rock pool in golden hour light",
  "glass-walled library reading room under full moon",
  "hidden lake house dock with lightning on the horizon",
  "thunderhead-lit submarine pen gate in dense fog",
  "wind-swept chicken coop yard at dusk",
  "cedar-scented dam overlook with firefly dusk",
  "honey-colored guard tower base in winter frost",
  "crystal-clear press room floor in morning mist",
  "curved rope bridge crossing under aurora",
  "silent waterfall base pool with drifting pollen",
  "salt-crusted music hall balcony with falling ash",
  "turquoise marina fuel dock in winter frost",
  "volcanic plantation veranda at twilight",
  "spruce-fringed sculpture garden path before a storm",
  "rock-hewn stockyard pen gate in winter frost",
  "hillside covered bridge interior at noon",
  "hand-painted subway mezzanine under bruised storm clouds",
  "breezy windmill cap platform with mirage shimmer",
  "half-submerged concert hall lobby before a storm",
  "petroleum-stained ferry terminal in dense fog",
  "steam-filled mission courtyard at twilight",
  "straw-roofed courtroom gallery in late spring",
  "dune-backed ice rink surface with wildfire smoke",
  "pine-scented dhow harbor quay with drifting pollen",
  "shingle-roofed airfield hangar with heat shimmer",
  "smoke-stained spa rock pool at dusk",
  "driftwood-strewn seawall promenade with lightning on the horizon",
  "wind-scoured stage loading dock under bruised storm clouds",
  "underground rail yard switch point in late spring",
  "heat-hazed stable yard under bruised storm clouds",
  "honey-colored highland bothy under aurora",
  "cliffside signal fire hilltop under rolling thunderheads",
  "gritty zipline launch deck in late spring",
  "spruce-fringed coral atoll lagoon in polar twilight",
  "pine-scented ferry terminal under bruised storm clouds",
  "smoke-stained quarry lake edge with lightning on the horizon",
  "marble observatory dome slit in river fog",
  "beached coral atoll lagoon in sea spray",
  "dusty lagoon mangrove edge in monsoon mist",
  "monsoon-soaked bakery courtyard in heavy snow",
  "pale wave-cut platform shore in heavy snow",
  "carved arcade corridor at dusk",
  "moonlit vineyard crush pad with firefly dusk",
  "tidal savanna waterhole bank with mirage shimmer",
  "hand-painted oyster farm rack line in sea spray",
  "harbor-side mausoleum steps with falling ash",
  "tapestry-lined market square arcades in morning mist",
  "heat-hazed butte overlook with heat shimmer",
  "half-submerged butte overlook under clear stars",
  "shadowed refectory hall in polar twilight",
  "whitewashed rooftop helipad under bruised storm clouds",
  "mud-brick bench overlook in golden hour light",
  "enchanted orchard ladder row in cherry blossom season",
  "silent catacomb passage in winter frost",
  "ancient aquarium tunnel in winter frost",
  "sodium-lit pantry stone cellar in sea spray",
  "sea-sprayed guard tower base with wildfire smoke",
  "bamboo-shaded bridge underpass in heat haze",
  "ash-covered seawall promenade under clear stars",
  "river-cut rose garden pergola at dusk",
  "balconied castle bailey after rain",
  "bleached marsh boardwalk in cherry blossom season",
  "wind-swept butte overlook in late spring",
  "cobbled rainforest stream ford in late spring",
  "pink-salt brewery yard in cherry blossom season",
  "candlelit cave temple with firefly dusk",
  "palm-fringed lagoon mangrove edge in monsoon mist",
  "lichen-stained ballroom balcony with mirage shimmer",
  "mirror-still food hall counter row at midnight",
  "tidal food hall counter row under aurora",
  "arched sea arch tide pool after rain",
  "polished vineyard crush pad under bruised storm clouds",
  "wrought-iron wharf crane shadow before a storm",
  "driftwood-strewn cave temple under aurora",
  "blue-hour street market tarp row under full moon",
  "rose-colored manor kitchen garden in morning mist",
  "heat-hazed zoo habitat moat edge with heat shimmer",
  "waterlogged woodshop floor after rain",
  "pink-salt town hall steps in polar twilight",
  "crystal-clear swamp cypress knee grove in monsoon mist",
  "flood-damaged spinning mill floor in morning mist",
  "dawn-lit sugar mill yard with heat shimmer",
  "vine-draped rock arch amphitheater under aurora",
  "gold-leaf fish ladder pool with wildfire smoke",
  "sunken seawall promenade with hoarfrost stillness",
  "river-cut sea cave mouth at twilight",
  "sandstone crossroads shrine at dusk",
  "cedar-scented vineyard crush pad in heavy snow",
  "dusty fountain plaza with hoarfrost stillness",
  "breezy park bandstand before a storm",
  "spruce-fringed crossroads shrine under low cloud",
  "dew-covered veranda overlooking bay with wildfire smoke",
  "ancient fjord village quay after rain",
  "sodium-lit dam overlook with lightning on the horizon",
  "moss-covered cable car station under full moon",
  "hillside courtroom gallery in polar twilight",
  "verdant mine cart tunnel during a downpour",
  "overgrown vaulted cellar aisle with firefly dusk",
  "ruined cable car station in winter frost",
  "rust-red reading nook alcove in late spring",
  "whitewashed pantry stone cellar in autumn color",
  "steam-filled promenade band shell in winter frost",
  "gritty mission courtyard with mirage shimmer",
  "autumn terrace vineyard row with falling ash",
  "blue-hour estate orangery under clear stars",
  "terracotta mill race channel under rolling thunderheads",
  "turquoise lumber mill deck in winter frost",
  "forest-edge cottage garden with drifting pollen",
  "broken fog-bound pier in heat haze",
  "vine-draped stone circle clearing at dawn",
  "crumbling auction house floor in winter frost",
  "salt-crusted farm silo base under aurora",
  "verdant sun deck over canyon with falling ash",
  "crumbling ballroom balcony with heat shimmer",
  "ruined valley floor stream at dawn",
  "quartz-lined colonnade walk at midnight",
  "scaffolded bench overlook with falling ash",
  "pale tower bridge walkway in polar twilight",
  "wind-scoured bridge underpass with firefly dusk",
  "glass-walled market square arcades with firefly dusk",
  "black-stone soap factory courtyard in monsoon mist",
  "straw-roofed cabin porch during a downpour",
  "stone-paved smokehouse shed in summer haze",
  "deserted ice rink surface in winter frost",
  "twilight courtroom gallery under aurora",
  "jade-green cottage garden in heat haze",
  "torch-lit apothecary cellar under bruised storm clouds",
  "reflective overlook rail under bruised storm clouds",
  "verdant ferry terminal with wildfire smoke",
  "salt-crusted racecourse paddock in monsoon mist",
  "tidal canal lock house after rain",
  "ice-bound tool shed yard at noon",
  "spruce-fringed snowfield camp under bruised storm clouds",
  "broken kitchen garden path in summer haze",
  "forest-edge desert arroyo bend in heavy snow",
  "bamboo-shaded volleyball court sand at dusk",
  "eroded narrow gorge bridge in late spring",
  "neon-lit crystal shop basement at noon",
  "misty courtroom gallery with firefly dusk",
  "hand-painted sea cave mouth with lightning on the horizon",
  "broken ruin chapel nave with falling ash",
  "emerald cliff dwelling in golden hour light",
  "pale rope bridge crossing under full moon",
  "copper-roofed ice cave chamber in heat haze",
  "enchanted veranda overlooking bay with falling ash",
  "pale kitchen garden path after rain",
  "dimly lit restaurant terrace in monsoon mist",
  "cobbled subway mezzanine with wildfire smoke",
  "arched yacht club pier with mirage shimmer",
  "midnight rotunda interior with firefly dusk",
  "sapphire atrium garden after rain",
  "turquoise subway mezzanine at twilight",
  "rock-hewn rock arch amphitheater during a downpour",
  "verdant perfume distillery room in morning mist",
  "indigo vineyard crush pad with lightning on the horizon",
  "sunken garden maze center in autumn color",
  "fog-draped stargazing platform in morning mist",
  "marble crater lake shore in cherry blossom season",
  "spruce-fringed creamery floor in late spring",
  "cloud-wrapped windmill cap platform in winter frost",
  "knotty-pine copper mine shaft under bruised storm clouds",
  "gilded summit cairn plateau in monsoon mist",
  "rust-red sculpture garden path with drifting pollen",
  "rain-darkened wave-cut platform shore under clear stars",
  "straw-roofed smokehouse shed at dawn",
  "ash-covered castle bailey in autumn color",
  "crumbling sail loft floor in monsoon mist",
  "volcanic tunnel portal mouth with lightning on the horizon",
  "pink-salt paper mill sluice under aurora",
  "open-air kiosk square in summer haze",
  "mirror-still hot spring pool at midnight",
  "copper-roofed crevasse edge camp at noon",
  "honey-colored grotto pool under clear stars",
  "hillside zoo habitat moat edge during a downpour",
  "reed-thatched hayfield lane under aurora",
  "dusty dockside warehouse in winter frost",
  "moonlit hotel rooftop pool with wildfire smoke",
  "pale locksmith shop bench in autumn color",
  "cedar-scented sea cave mouth before a storm",
  "starlit chicken coop yard with wildfire smoke",
  "snow-dusted film set facade in autumn color",
  "hidden monastery refectory at noon",
  "curved ruin chapel nave in late spring",
  "fog-draped dried riverbed crossing under rolling thunderheads",
  "dimly lit dried riverbed crossing under clear stars",
  "storm-lashed stone circle clearing in monsoon mist",
  "abandoned highland bothy under rolling thunderheads",
  "weathered factory floor in morning mist",
  "cloud-wrapped tropical fish pond deck at noon",
  "sunken subway mezzanine in summer haze",
  "silver-birch swamp cypress knee grove with wildfire smoke",
  "monsoon-soaked street market tarp row at dawn",
  "neon-lit patio fire pit in river fog",
  "lime-washed marsh boardwalk under aurora",
  "dusty sail loft floor with mirage shimmer",
  "pale zipline launch deck in river fog",
  "tidal stargazing platform at dusk",
  "sun-baked kiosk square at dusk",
  "rust-red waiting pier shelter under aurora",
  "straw-roofed ballroom balcony in summer haze",
  "turquoise highland bothy in polar twilight",
  "balconied catacomb passage under aurora",
  "open-air hospital courtyard at dusk",
  "pine-scented canyon overlook with drifting pollen",
  "mirror-still farm silo base with heat shimmer",
  "forest-edge winery tasting room with hoarfrost stillness",
  "canopied golf clubhouse terrace after rain",
  "abandoned volleyball court sand in cherry blossom season",
  "balconied catacomb passage at dusk",
  "rain-darkened bullring gate in summer haze",
  "ochre hotel rooftop pool in dense fog",
  "obsidian tribunal steps at midnight",
  "black-stone catacomb passage under rolling thunderheads",
  "grassy spring house stone floor under bruised storm clouds",
  "arched abbey crypt in summer haze",
  "sun-baked playground after rain with wildfire smoke",
  "rain-darkened skate park bowl before a storm",
  "shadowed orchard ladder row with lightning on the horizon",
  "basalt river bend sandbar after rain",
  "azure carriage house during a downpour",
  "wind-scoured fairground carousel platform in sea spray",
  "basalt fire station bay in late spring",
  "cedar-scented summit cairn plateau in late spring",
  "reflective market square arcades in winter frost",
  "ivy-covered mausoleum steps in golden hour light",
  "moss-covered apothecary cellar in winter frost",
  "driftwood-strewn ice rink surface under low cloud",
  "overgrown treehouse platform under clear stars",
  "rust-red mosque courtyard fountain under aurora",
  "sun-bleached circus ring at dawn",
  "stone-paved engine shed with lightning on the horizon",
  "shadowed dockside warehouse under bruised storm clouds",
  "pebbled bakery courtyard with mirage shimmer",
  "spruce-fringed guard tower base at dawn",
  "moss-covered paper mill sluice under low cloud",
  "dusty estate orangery under rolling thunderheads",
  "flood-damaged ice rink surface with wildfire smoke",
  "lava-black lodge great room under rolling thunderheads",
  "mirror-still reef flat channel at dawn",
  "sun-baked ruin chapel nave in heat haze",
  "lava-black skybridge between towers at twilight",
  "midnight storage loft ladder in morning mist",
  "cypress-lined marsh boardwalk in polar twilight",
  "old-growth rainforest stream ford with wildfire smoke",
  "thunderhead-lit castle bailey under bruised storm clouds",
  "hillside dune slack hollow under aurora",
  "basalt canyon overlook at noon",
  "silent ferry terminal in heavy snow",
  "lime-washed passage tomb entrance with firefly dusk",
  "quartz-lined nursery greenhouse before a storm",
  "cedar-scented monorail station in monsoon mist",
  "curved cable car station in summer haze",
  "polished mosque courtyard fountain in heavy snow",
  "bioluminescent outcrop belay ledge with heat shimmer",
  "broken temple bell courtyard under bruised storm clouds",
  "autumn library reading room at noon",
  "patchwork music hall balcony at noon",
  "basalt hill fort ditch with heat shimmer",
  "verdant pond lily pad edge with mirage shimmer",
  "blue-hour hotel rooftop pool at twilight",
  "wrought-iron veranda overlooking bay under bruised storm clouds",
  "half-submerged houseboat deck with firefly dusk",
  "tidal crater lake shore under full moon",
  "patchwork vaulted cellar aisle in golden hour light",
  "twilight synagogue courtyard with falling ash",
  "ivy-covered backlot street with mirage shimmer",
  "coral-fringed ghost town main street in dense fog",
  "forest-edge spa rock pool at dusk",
  "coral-fringed observatory dome slit at noon",
  "tapestry-lined maelstrom viewpoint in heavy snow",
  "breezy coffee roastery with hoarfrost stillness",
  "palm-fringed storage loft ladder with falling ash",
  "old-growth lookout tower cab under clear stars",
  "blue-hour lido deck at twilight",
  "indigo forge courtyard after rain",
  "carved stone circle clearing in cherry blossom season",
  "broken dog park gate at twilight",
  "petroleum-stained tennis court fence line under rolling thunderheads",
  "pale moorland trail crest with firefly dusk",
  "cliffside engine shed after rain",
  "arched geyser boardwalk in winter frost",
  "emerald lake house dock with firefly dusk",
  "turquoise mead hall hearth before a storm",
  "dew-covered spring house stone floor with wildfire smoke",
  "monsoon-soaked cable car station under rolling thunderheads",
  "honey-colored fairground carousel platform in late spring",
  "rose-colored hill fort ditch under aurora",
  "hand-painted fishing hut pier before a storm",
  "river-cut zipline launch deck after rain",
  "waterlogged treehouse platform with heat shimmer",
  "cobbled rotunda interior after rain",
  "shadowed assembly hall in polar twilight",
  "ice-bound metro platform after rain",
  "rust-red jetty end with drifting pollen",
  "neon-lit pod village boardwalk with drifting pollen",
  "crumbling cave temple in cherry blossom season",
  "sapphire cave temple under clear stars",
  "glass-walled bullring gate with wildfire smoke",
  "misty bowling alley lane before a storm",
  "pale bridge underpass with hoarfrost stillness",
  "ancient heliport pad with wildfire smoke",
  "azure soundstage alley set in heat haze",
  "carved lake house dock in polar twilight",
  "lichen-stained pod village boardwalk under bruised storm clouds",
  "grassy butte overlook in monsoon mist",
  "sandstone geyser boardwalk under clear stars",
  "black-stone spa rock pool in morning mist",
  "sandstone pavilion on lake during a downpour",
  "reflective taxi rank corner in morning mist",
  "beached rope bridge crossing in monsoon mist",
  "cliffside terrace vineyard row at twilight",
  "autumn catacomb passage with mirage shimmer",
  "emerald sail loft floor in autumn color",
  "candlelit tower bridge walkway with heat shimmer",
  "basalt ferry terminal at noon",
  "narrow workshop annex yard at noon",
  "hillside monorail station in morning mist",
  "black-stone street market tarp row in monsoon mist",
  "salt-crusted pond lily pad edge in autumn color",
  "sun-bleached rice paddy bund path under clear stars",
  "moss-covered thermal mud pool before a storm",
  "granite hot spring pool with heat shimmer",
  "heat-hazed narrow gorge bridge in river fog",
  "fog-draped dhow harbor quay during a downpour",
  "patchwork wharf crane shadow during a downpour",
  "crystal-clear rice paddy bund path with firefly dusk",
  "snow-dusted paper mill sluice in polar twilight",
  "deserted medina covered souk under bruised storm clouds",
  "pink-salt marsh boardwalk at dawn",
  "pink-salt hot spring pool at midnight",
  "lime-washed engine shed with lightning on the horizon",
  "overgrown archipelago cove with lightning on the horizon",
  "beached observatory dome slit with heat shimmer",
  "ancient sunflower field lane in polar twilight",
  "palm-fringed stargazing platform in golden hour light",
  "black-stone overlook rail with hoarfrost stillness",
  "balconied customs warehouse in river fog",
  "thunderhead-lit embassy courtyard at noon",
  "quartz-lined courtyard fountain before a storm",
  "terracotta aviary dome with heat shimmer",
  "heat-hazed rice paddy bund path at dawn",
  "sunken brewery yard under clear stars",
  "river-cut coastal bluff path under low cloud",
  "enchanted archipelago cove at dusk",
  "upland paper mill sluice in heavy snow",
  "midnight mausoleum steps under low cloud",
  "hillside pier end gazebo after rain",
  "cliffside warehouse mezzanine with hoarfrost stillness",
  "pale waiting pier shelter with drifting pollen",
  "quartz-lined deck overlooking valley in winter frost",
  "sun-baked opera house foyer in cherry blossom season",
  "ancient glacier cave mouth in golden hour light",
  "crumbling reservoir spillway before a storm",
  "pink-salt bullring gate at midnight",
  "pale lime kiln ruin at dusk",
  "polished crossroads shrine in morning mist",
  "blue-hour plantation veranda with lightning on the horizon",
  "dawn-lit tollhouse lane under aurora",
  "twilight lido deck in summer haze",
  "flood-damaged cemetery chapel in autumn color",
  "underground motor pool yard at noon",
  "dawn-lit rose garden pergola in sea spray",
  "crumbling fjord village quay in heat haze",
  "honey-colored river bend sandbar with lightning on the horizon",
  "blue-hour mausoleum steps under bruised storm clouds",
  "glacial sugar mill yard under rolling thunderheads",
  "forest-edge herb garden terrace at dawn",
  "iron-clad cheese cave in summer haze",
  "balconied veranda overlooking bay in golden hour light",
  "gritty market square arcades in cherry blossom season",
  "chalk-white mine cart tunnel with hoarfrost stillness",
  "frosted bird sanctuary blind at twilight",
  "bioluminescent treehouse platform in cherry blossom season",
  "breezy pier end gazebo before a storm",
  "gritty refectory hall with heat shimmer",
  "river-cut refectory hall at noon",
  "heat-hazed train carriage depot in morning mist",
  "heat-hazed shrine torii path before a storm",
  "steam-filled bus depot in morning mist",
  "sodium-lit covered bridge interior in sea spray",
  "smoke-stained racecourse paddock under clear stars",
  "carved fjord village quay under bruised storm clouds",
  "overgrown tropical fish pond deck in river fog",
  "spruce-fringed bamboo grove clearing with hoarfrost stillness",
  "waterlogged quarry lake edge in river fog",
  "lime-washed snorkel lagoon shelf in sea spray",
  "granite gymnasium floor in golden hour light",
  "starlit apothecary cellar during a downpour",
  "ivy-covered wagon trail ford in winter frost",
  "canopied tollhouse lane in golden hour light",
  "overgrown tennis court fence line during a downpour",
  "sun-bleached tollhouse lane in autumn color",
  "patchwork barn loft at dawn",
  "smoke-stained studio backlot alley after rain",
  "stone-paved pump house intake in late spring",
  "storm-lashed museum rotunda with wildfire smoke",
  "flood-damaged perfume distillery room under rolling thunderheads",
  "bamboo-shaded pod village boardwalk in autumn color",
  "verdant bamboo grove clearing at dusk",
  "torch-lit yurt camp circle under clear stars",
  "weathered arcade corridor under aurora",
  "curved quay stone steps with mirage shimmer",
  "dew-covered auction house floor with firefly dusk",
  "twilight inn courtyard in polar twilight",
  "lime-washed archive vault under low cloud",
  "upland tribunal steps during a downpour",
  "slate-roofed tool shed yard in autumn color",
  "torch-lit hayfield lane in heat haze",
  "shadowed studio backlot alley under low cloud",
  "pink-salt clock tower interior in monsoon mist",
  "driftwood-strewn outcrop belay ledge in late spring",
  "silver-birch pier end gazebo in river fog",
  "cloud-wrapped rainforest stream ford in summer haze",
  "carved marsh boardwalk in river fog",
  "driftwood-strewn customs warehouse under full moon",
] as const;
