function randomInt(max: number): number {
  if (max <= 0) {
    return 0;
  }
  const array = new Uint32Array(1);
  crypto.getRandomValues(array);
  return array[0]! % max;
}

function pick<T>(items: readonly T[]): T {
  return items[randomInt(items.length)]!;
}

const SETTING_ADJECTIVES = [
  "abandoned",
  "sunlit",
  "mist-shrouded",
  "neon-drenched",
  "frost-covered",
  "salt-stained",
  "wind-battered",
  "candlelit",
  "rain-slick",
  "dust-hazed",
  "overgrown",
  "polished",
  "crumbling",
  "mirror-still",
  "smoke-filled",
  "moonlit",
  "sun-bleached",
  "shadow-dappled",
  "flood-lit",
  "ice-locked",
  "copper-patina",
  "lichen-covered",
  "sodium-vapor",
  "haze-softened",
  "storm-lashed",
  "ember-warm",
  "tide-pooled",
  "snow-drifted",
  "vine-choked",
  "glass-walled",
  "timber-framed",
  "basalt-black",
  "quartz-glittering",
  "mud-spattered",
  "silk-draped",
  "iron-rusted",
  "marble-cool",
  "bamboo-screened",
  "clay-fired",
  "peat-smelling",
  "granite-sheltered",
  "sand-scoured",
  "kelp-strewn",
  "ash-dusted",
  "prism-split",
  "mirage-shimmering",
  "aurora-lit",
  "bioluminescent",
  "steam-wreathed",
  "petroleum-rainbow",
  "lichen-encrusted",
  "salt-crusted",
  "charcoal-smoked",
  "mold-spotted",
  "sun-scorched",
  "frost-rimed",
  "oil-slick",
  "mica-flecked",
  "obsidian-gloss",
  "chalk-dusted",
  "honey-lit",
  "sodium-amber",
  "ultraviolet-hazed",
] as const;

const ARCHITECTURE_TYPES = [
  "train station concourse",
  "glass atrium",
  "brick kiln hall",
  "timber mill loft",
  "stone bell tower base",
  "concrete bunker gallery",
  "wooden pier pavilion",
  "steel gantry walkway",
  "domed reading room",
  "vaulted wine cave",
  "cast-iron market hall",
  "limestone cloister",
  "shipping container yard office",
  "radio telescope dish floor",
  "planetarium outer ring",
  "aqueduct channel walk",
  "drawbridge control house",
  "lighthouse keeper stair",
  "grain silo interior ladder",
  "icehouse loading bay",
  "cannery packing floor",
  "textile mill spinning room",
  "brewery fermentation hall",
  "distillery still room",
  "charcoal kiln mound",
  "salt pan drying shed",
  "obsidian workshop court",
  "jade carving studio",
  "spice grading warehouse",
  "tea auction room",
  "silk reeling shed",
  "coral research tank deck",
  "kelp drying rack platform",
  "apiary extraction room",
  "mycology lab greenhouse",
  "seed bank cold room anteroom",
  "cartography tracing hall",
  "astrolabe repair bench room",
  "orchestra pit access tunnel",
  "opera fly tower catwalk",
  "film soundstage corner",
  "matte painting glass stage",
  "stop-motion puppet stage",
  "natural history diorama hall",
  "mineralogy display niche",
  "fossil prep lab window",
  "meteorite storage vault antechamber",
  "particle accelerator service tunnel",
  "planetarium gift shop mezzanine",
  "film color grading suite",
  "sound mixing dub stage",
  "hydroponic spiral greenhouse",
  "particle accelerator cryostat hall",
  "deep-sea pressure hull chamber",
  "orbital solar array maintenance ring",
  "desalination membrane hall",
  "vertical mushroom fruiting room",
  "automated fulfillment robot aisle",
  "glassblowing glory hole studio",
  "letterpress type case hall",
] as const;

const TERRAIN_FEATURES = [
  "cliffside",
  "riverside",
  "lakeshore",
  "dune crest",
  "canyon rim",
  "volcano slope",
  "glacier moraine",
  "mangrove channel",
  "tidal flat",
  "coral shelf",
  "karst sinkhole edge",
  "badlands ridge",
  "steppe hollow",
  "fjord wall",
  "mesa top",
  "ravine floor",
  "waterfall plunge pool",
  "geyser field boardwalk",
  "salt pan hex crack",
  "peat bog hummock",
  "lava field fissure",
  "sandbar spit",
  "estuary mudflat",
  "alpine cirque",
  "cloud forest saddle",
  "savanna kopje",
  "delta distributary bank",
  "oasis palm fringe",
  "permafrost polygon shore",
  "cypress swamp boardwalk end",
  "red rock amphitheater lip",
  "basalt column causeway",
  "granite tor summit",
  "schist quarry bench",
  "marble terrace overlook",
  "coral atoll lagoon edge",
  "ice shelf pressure ridge",
  "sandstone arch throat",
  "limestone pavement grike",
  "volcanic tuff chimney field",
  "alluvial fan toe",
  "hanging valley lip",
  "coastal stack base",
  "reef flat channel",
  "kelp forest surface lane",
  "monsoon waterfall terrace",
  "dry wash arroyo bend",
  "prairie pothole rim",
  "boreal muskeg edge",
  "heathland gorse hollow",
  "volcanic tuff chimney field",
  "karst polje seasonal lake",
  "raised bog quaking mat edge",
  "coral bommie lagoon pass",
  "granite tor wind-scoured summit",
  "limestone pavement grike maze",
  "black sand dune slip face",
  "salt marsh tidal creek bend",
  "alpine scree slope bench",
] as const;

const MICRO_STRUCTURES = [
  "watchtower",
  "pavilion",
  "bunker mouth",
  "signal hut",
  "waystation porch",
  "survey cairn shelter",
  "shepherd bothy",
  "fishing weir hut",
  "salt windmill base",
  "water wheel house",
  "draw well curb",
  "mile marker shrine",
  "roadside chapel niche",
  "ferry landing shed",
  "canal lock chamber",
  "railway water tower foot",
  "telegraph relay shack",
  "weather station mast base",
  "fire lookout cab",
  "smuggler cave mouth",
  "mine adit entrance",
  "quarry cable anchor",
  "dam inspection gallery",
  "spillway gate house",
  "pumping station intake",
  "desalination pipe mouth",
  "wind turbine nacelle access",
  "solar array inverter hut",
  "geothermal wellhead pad",
  "oil derrick catwalk",
  "lighthouse foghorn shed",
  "buoy maintenance dock",
  "harbor crane cab",
  "shipyard dry dock lip",
  "submarine pen gate",
  "airship mooring mast foot",
  "hang glider launch ramp",
  "ski lift bullwheel housing",
  "cable car mid station",
  "funicular upper terminus",
  "zip line landing platform",
  "climbing bolt belay ledge",
  "caving pitch head",
  "treehouse rope bridge end",
  "floating research platform",
  "ice fishing hut cluster edge",
  "nomad tent circle outer ring",
  "caravanserai courtyard gate",
  "border checkpoint lane",
  "customs inspection bay",
  "abandoned ski lift tower foot",
  "floating solar pontoon dock",
  "storm drain outfall barricade",
  "railway turntable pit rim",
  "coastal foghorn bunker mouth",
  "wind turbine blade storage yard",
  "geothermal wellhead valve pad",
  "satellite uplink radome base",
  "cargo airship mooring mast",
] as const;

const REGION_EPITHETS = [
  "Scandinavian",
  "Andean",
  "Sahel",
  "Baltic",
  "Caucasus",
  "Maghrebi",
  "Indochinese",
  "Polynesian",
  "Siberian",
  "Patagonian",
  "Appalachian",
  "Mesopotamian",
  "Levantine",
  "Iberian",
  "Balkan",
  "Caribbean",
  "Melanesian",
  "Himalayan",
  "Azorean",
  "Sicilian",
  "Crimean",
  "Karelian",
  "Sami",
  "Berber",
  "Maori",
  "Ainu",
  "Quechua",
  "Mayan",
  "Inuit",
  "Bedouin",
  "Rajasthani",
  "Kerala",
  "Sichuan",
  "Yunnan",
  "Hokkaido",
  "Okinawan",
  "Basque",
  "Corsican",
  "Sardinian",
  "Dalmatian",
  "Transylvanian",
  "Saxon",
  "Flemish",
  "Frisian",
  "Welsh",
  "Cornish",
  "Hebridean",
  "Orkney",
  "Svalbard",
  "Lapland",
  "Tuareg",
  "Amazigh",
  "Khmer",
  "Burmese",
  "Tibetan",
  "Uyghur",
  "Kurdish",
  "Hmong",
  "Pashtun",
  "Zulu",
  "Yoruba",
] as const;

const TIME_AND_WEATHER_PHRASES = [
  "at first light",
  "at blue hour",
  "during a downpour",
  "after snowfall",
  "in heat haze",
  "under aurora",
  "in monsoon mist",
  "at high noon",
  "during a sandstorm edge",
  "in river fog",
  "at twilight",
  "during a lightning storm",
  "in cherry-blossom drift",
  "after harvest dust",
  "in sea spray",
  "during a whiteout",
  "at golden hour",
  "in coal-smoke winter air",
  "during a haboob front",
  "in pollen haze",
  "at moonrise",
  "during a dry lightning watch",
  "in wildfire smoke",
  "after a flash flood",
  "in hoarfrost stillness",
  "during a gale warning",
  "in equatorial downpour break",
  "at siesta hour silence",
  "during a midnight sun",
  "in polar twilight",
  "during a heat lightning watch",
  "in ash fall after eruption",
  "at misty dawn after frost",
  "during a kelp-strewn low tide",
  "in diesel-smoke winter dusk",
  "at mirror-still dawn on water",
  "during a dust devil crossing",
  "in ozone-sharp post-storm air",
  "at firefly dusk in humid air",
] as const;

const ACTION_ENVIRONMENT_BEATS = [
  "with debris scattering from the impact",
  "with water exploding outward from the stride",
  "with dust plume trailing behind",
  "with sparks skidding across metal",
  "with fabric whipping in the gust",
  "with leaves torn loose in the wake",
  "with sand spraying from the landing",
  "with snow crystals bursting on contact",
  "with mud splattering up the calves",
  "with glass shards glittering on the floor",
  "with rope tension vibrating audibly",
  "with steam venting from a pipe",
  "with embers spiraling upward",
  "with rain streaking diagonally through frame",
  "with hail bouncing off stone",
  "with gravel skittering underfoot",
  "with ice cracking under the boot",
  "with foam surging around the ankles",
  "with oil rainbow sheen on wet concrete",
  "with neon reflections streaking in puddles",
  "with confetti suspended mid-air",
  "with steam venting from a grate",
  "with pollen clouds catching sidelight",
  "with shattered ice spraying outward",
  "with rope fibers fraying under tension",
  "with chalk dust hanging in a beam",
  "with sparks tracing an arc weld line",
  "with feathers drifting on a gust",
  "with oil rainbow sheen rippling on water",
] as const;

export function composeSceneLocation(): string {
  const roll = randomInt(100);

  if (roll < 30) {
    return `${pick(SETTING_ADJECTIVES)} ${pick(ARCHITECTURE_TYPES)} ${pick(TIME_AND_WEATHER_PHRASES)}`;
  }

  if (roll < 55) {
    return `${pick(TERRAIN_FEATURES)} ${pick(MICRO_STRUCTURES)} ${pick(TIME_AND_WEATHER_PHRASES)}`;
  }

  if (roll < 75) {
    return `${pick(REGION_EPITHETS)} ${pick(ARCHITECTURE_TYPES)} ${pick(TIME_AND_WEATHER_PHRASES)}`;
  }

  if (roll < 90) {
    return `${pick(SETTING_ADJECTIVES)} ${pick(TERRAIN_FEATURES)} ${pick(MICRO_STRUCTURES)}`;
  }

  return `${pick(REGION_EPITHETS)} ${pick(TERRAIN_FEATURES)} ${pick(TIME_AND_WEATHER_PHRASES)}`;
}

/** @deprecated Use composeSceneLocation */
export const composeCharacterLocation = composeSceneLocation;

export function composeActionLocation(): string {
  const roll = randomInt(100);

  if (roll < 35) {
    return `${pick(SETTING_ADJECTIVES)} ${pick(TERRAIN_FEATURES)} ${pick(MICRO_STRUCTURES)} ${pick(ACTION_ENVIRONMENT_BEATS)}`;
  }

  if (roll < 60) {
    return `${pick(TERRAIN_FEATURES)} ${pick(ARCHITECTURE_TYPES)} ${pick(ACTION_ENVIRONMENT_BEATS)}`;
  }

  if (roll < 80) {
    return `${pick(REGION_EPITHETS)} ${pick(TERRAIN_FEATURES)} ${pick(TIME_AND_WEATHER_PHRASES)} ${pick(ACTION_ENVIRONMENT_BEATS)}`;
  }

  return `${composeSceneLocation()} ${pick(ACTION_ENVIRONMENT_BEATS)}`;
}
